### ISSUE TITLE
Pedidos: campo de observaciones "externo" e "interno"

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#10]
En la sección de pedidos, debería haber dos campos de observaciones: uno para que el usuario pueda escribir lo que le parezca, y otro interno para las instrucciones del administrador a los transportistas. El primero puede aparecer en los emails de confirmación, en la página para editar pedidos... El segundo sólo tiene que aparecerle al administrador y a los transportistas.

Por defecto, al crearse cada pedido, las observaciones del cliente se copian en el campo de observaciones "interno" (para que éste no esté vacío).

**Comment by sirym** [comment]
Añadidas.
En la base de datos se llaman: observaciones_cliente, observaciones_admin
