### ISSUE TITLE
Observaciones de pedidos: hacer que aparezcan al administrador

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#100]
Actualmente, las observaciones de un pedido (no de una etapa, sino del pedido global) no aparecen por ninguna parte. Hay que añadirlas en la página de admin. en algún sitio, y hacer que aparezcan también en el email al transportista.

**Comment by PaulJBis** [comment]
Hecho. El único problema es que las observaciones no aparecen como un tooltip encima de la tabla, sino al lado de ésta.

**Comment by sirym** [comment]
Añadido como popover ;)
