### ISSUE TITLE
Admin.: mejorar el selector de pueblos en la página para crear un nuevo pedido

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#104]
-Tiene que haber un buscador, igual que en la página pública (es decir: usar selectpicker).
-Por defecto, al seleccionar un pueblo de origen, debe aparecer el siguiente pueblo como destino.
-Al añadir nuevos envíos, el pueblo de origen debe ser por defecto el de destino del envío anterior.
-Se debe poder seleccionar al transportista (aparece elegido por defecto el que está asignado, pero el administrador tiene que poder cambiarlo).

**Comment by sirym** [comment]
Punto 1 y 2 hechos

**Comment by sirym** [comment]
Los puntos 3 y 4 me parecen muy confusos ya que al cambiar el pueblo de destino del primer pueblo se cambiarían automaticamente los siguientes en cadena y los repartidores ya que se realiza de manera dinámica.

**Comment by PaulJBis** [comment]
Ha contestado el cliente. Dice que quiere que aparezcan esos campos sólo inicialmente, pero que luego no se actualicen; es decir, al dar al botón "Añadir nuevo pedido", se crea por defecto el pueblo de origen como el destino anterior, pero luego no hace falta que vayan cambiando.

**Comment by sirym** [comment]
Punto 3 hecho

**Comment by sirym** [comment]
Completado

**Comment by sirym** [comment]
¿Porque se ha reabierto este? ¿Es por lo de #118?

**Comment by PaulJBis** [comment]
Creía que lo había puesto en un comentario... WTF? ¿Se lo ha comido esto?
Lo he reabierto porque me he dado cuenta de que se tendrían que rellenar el nº de bultos y la fecha de forma automática también (cada etapa que salga con el día siguiente al de la fecha anterior). Es algo obvio, pero se me olvidó ponerlo en la especificación inicial.

**Comment by sirym** [comment]
Añadido

**Comment by PaulJBis** [comment]
Bug: en el selector de fechas, al añadir un 2º pedido, la fecha del 2º pedido es la del día siguiente del 1º pedido... pero de 10 años después (2025 en vez de 2015). Si elegimos en el primer pedido el último día de un mes (30 abril), el 2º pedido sale con el día 2 del mes siguiente (2 de mayo de 2025).

**Comment by PaulJBis** [comment]
Viendo el analizador de red, parece que el PHP (masPedidos.php) está devolviendo una página con la fecha correcta, así que el error estará en el Javascript.

**Comment by sirym** [comment]
corregido
