### ISSUE TITLE
Admin.: poder añadir múltiples envíos para un mismo cliente

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#11]
En la página de administración, se debería poder añadir varios envíos de una sola vez con los datos de un mismo cliente. Esto es útil para introducir los datos de aquellos clientes que vayan a hacerse, por ejemplo, todo el camino de Santiago, y quieran que se les transporten los equipajes a lo largo de sucesivas etapas.

**Comment by sirym** [comment]
Completado
