### ISSUE TITLE
Admin.: mejorar el popup para editar entradas

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#112]
El popup que sale para editar pedidos, clientes...:

-Sería mejor si apareciera justo donde esté la ventana del navegador, en vez de arriba del todo en la página (relevante para páginas muy largas, que no quepan en una pantalla).
-Los botones de "Guardar" y "Borrar" tienen que estar más accesibles, que no haya que hacer scroll para llegar a ellos.

**Comment by PaulJBis** [comment]
Lo primero está hecho. Lo segundo no lo está. Se podría solucionar poniendo en una sola linea:

-Fecha y repartidor.
-Estado y Nº bultos.

De esta forma se podría ahorrar algo de espacio en la altura del popup.

**Comment by sirym** [comment]
He reducido la altura del popup de esta manera. A ver que tal.

**Comment by PaulJBis** [comment]
Falta por hacer en:

-Clientes.
-Hospedajes.
-Pueblos.

Modificar en este orden de prioridad.

**Comment by sirym** [comment]
Hecho
