### ISSUE TITLE
Modificar pedidos: si hacemos una modificación en la que haya que pagar más dinero, la pag. de resultados sale mal

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#116]
Si hacemos una modificación en un pedido y tenemos que pagar más, al volver del TPV, en la página de resultado que nos sale aparece la lista de pedidos dos veces.
(Esto sólo pasa en la página, no en el email de recibo).

**Comment by sirym** [comment]
Corregido
