### ISSUE TITLE
Al borrarse un envío de un pedido, en el email de confirmación sale aún el envío borrado

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#119]
Si borramos un envío de un pedido, se borra correctamente, pero en el email de confirmación sigue saliendo el envío borrado.

**Comment by sirym** [comment]
He estado revisando esto y lo he hecho, pero me he dado cuenta de que quizás fuese mejor que apareciese, pero con el estado entre paréntesis, como he puesto en algunos casos: ejemplo
Datos del envío número 1 (Cancelado)

**Comment by PaulJBis** [comment]
Me parece bien, pero muestra el texto del envío cancelado tachado.

**Comment by sirym** [comment]
Hecho
