### ISSUE TITLE
Al cancelar un envío, el envío cancelado debería aparecer tachado en todo momento

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#120]
Cuando cancelamos un envío de un pedido, en la página que sale antes de confirmar el cambio, no aparece tachado.

En la página que aparece después de volver del TPV (si hemos hecho a la vez un cambio que implica pago), sí aparece tachado (creo), pero aun así habría que verificarlo para asegurarse de que sale tachado en todos los casos.

**Comment by sirym** [comment]
Corregido
