### ISSUE TITLE
Admin.: desactivar el botón de "Añadir más pedidos" si el primer envío está vacío

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#121]
Ahora mismo, si añadimos un pedido y pulsamos el botón de "Añadir nuevo envío" cuando el primero está vacío, nos permite añadirlo, pero sale un error "Notice: Undefined offset: 2 in /home/caminofaky/www/NEW/app/modules/Envio/masPedidos.php on line 28".

Lo que hay que hacer es desactivar el botón de "Añadir más pedidos deel mismo cliente" hasta que en el envío anterior estén introducidos los datos necesarios.

**Comment by sirym** [comment]
Juraría que lo había bloqueado

**Comment by PaulJBis** [comment]
Aparece en gris, pero si lo pulsas te responde y te sale la siguiente etapa.

**Comment by PaulJBis** [comment]
Sigue pasando, pero esto tiene ahora menos importancia. Le cambio el milestone al bug.

**Comment by sirym** [comment]
Hecho
