### ISSUE TITLE
Admin.:añadir una "X" para borrar una etapa añadida por error

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#128]
Al añadir un pedido, es común equivocarse y pulsar al botón de "Añadir nueva etapa", cuando no hay ya ninguna etapa adicional. En ese caso, se debería poder pulsar una "X" y quitar el DIV de la última etapa, que acabamos de añadir (las anteriores las podemos dejar).

**Comment by sirym** [comment]
Hecho
