### ISSUE TITLE
Modificar código para que la página pública soporte varios idiomas

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#13]
La página pública debe soportar textos en varios idiomas.

**Comment by sirym** [comment]
Código adaptado

**Comment by PaulJBis** [comment]
¿Los enlaces? ¿No bastaría con añadir el idioma como una cookie más, para importarla como variable de sesión?

**Comment by sirym** [comment]
Añadidos dos sistemas de identificación de lenguaje: mediante el lenguaje del navegador y mediante las banderitas del header (se guardan en una cookie).
