### ISSUE TITLE
Email para repartidores: maquetar mejor

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#132]
El email para los repartidores tiene que estar mejor maquetado:

-No poner la columna de email.
-Maquetar para que quepa en un folio en vertical.

**Comment by PaulJBis** [comment]
Realizados cambios. Pendiente de que el cliente diga si se imprimen bien.

**Comment by sirym** [comment]
¿Esto en que quedó?

**Comment by PaulJBis** [comment]
En nada. No ha habido más quejas sobre ese tema.
