### ISSUE TITLE
Email para usuario: a veces no muestra los precios tras una modificación

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#139]
Hacemos modificaciones en un pedido: borrar etapas, añadir bultos... pero que supongan tener que cobrar al final (es decir, ir al TPV). El email que llega al usuario aparece con "0 euros" como precio de cada etapa.

**Comment by albertoi** [comment]
Corregido

**Comment by sirym** [comment]
Corregido
