### ISSUE TITLE
Admin.: el desplegable de la localidad de destino no sale centrado en la localidad seleccionada

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#141]
Al crear un nuevo pedido en admin., al seleccionarse una localidad de origen, la localidad de destino aparece seleccionada también... pero al pulsar en el desplegable, éste aparece centrado en el principio de la lista, no en el pueblo seleccionado.

**Comment by sirym** [comment]
Parece ser que al haber actualizado el selectpicker se corrigió el problema ahora que lo estoy revisando
