### ISSUE TITLE
Admin.: al editar un pedido con muchos envíos, al editar cada envío deberíamos volver a la lista de ese pedido

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#142]
Editamos un pedido con muchos envíos. Editamos uno de los envíos, y al guardar los cambios... nos redirige a la página principal de admin. Sería deseable que redirigiera a la lista de envíos de ese pedido.

**Comment by sirym** [comment]
Completado

**Comment by sirym** [comment]
Reabro porque no había leido bien el bug, pensé que era al añadir un nuevo pedido, no al editarlo

**Comment by sirym** [comment]
Solucionado
