### ISSUE TITLE
Admin.: lentitud al añadir nuevos pedidos con muchos envíos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#143]
En la página de admin., al añadir nuevos envíos, tarda mucho cuando hay muchos envíos (a partir de 5 o 6).

**Comment by sirym** [comment]
He conseguido aumentar muuucho la velocidad ajustando partes del codigo de los selectpicker. He puesto el refresh solo en los elementos necesarios y los momentos necesarios
