### ISSUE TITLE
Admin.: escribir interface para editar pedidos completos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#148]
Además de la página de envíos, debería haber una página dedicada para editar pedidos (con todos sus envíos). En ella se debería poder, por ejemplo, borrar un pedido vacío (sin envíos), o cambiar de una vez el estado de todos los envíos.

**Comment by sirym** [comment]
Añadidas opciones para añadir bultos y estado globales para todo el pedido al crear uno nuevo
