### ISSUE TITLE
"Carrito de compra" para público

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#156]
Que el usuario, al hacer su envío, pueda editar y/o borrar las etapas que ya tiene hechas.

**Comment by PaulJBis** [comment]
Sería deseable que, además de enlaces para editar y borrar cada etapa, aparecieran los precios de cada etapa, y que se actualizaran cada vez que el usuario edita o borra los datos de una etapa.

**Comment by sirym** [comment]
Pero eso va a estar cambiando constantemente y confundiendo al cliente, ya que realmente hasta que no termina no sabe el precio de la etapa, porque varia si añade otra mas y tal

**Comment by PaulJBis** [comment]
Lo que confunde a la gente, vistos los emails que llegan, es no saber el precio hasta tener que pagar. No tiene por qué suponer un problema, puesto que hay una página de tarifas en donde están explicados claramente los precios. Además, la gente suele entender intuitivamente eso de que "cuanto mayor  es la compra, mayores son los descuentos".

**Comment by PaulJBis** [comment]
Especificación: ¿qué hacer si, al editar una etapa, se pone una fecha o pueblo de inicio/final iguales a los de una etapa ya existente?

1) Al hacerlo, debe aparecer una alerta indicándolo, pero se le debe permitir (porque es posible que esté, por ejemplo, moviendo todas las etapas un día, y lo esté haciendo etapa a etapa).
2) Deben aparecer las etapas con fecha o pueblo idénticos en rojo en la lista.
2) Si el usuario intenta terminar el pedido y pagar, no le debe dejar, y debe aparecer un error indicando esto.

**Comment by sirym** [comment]
Hecho
