### ISSUE TITLE
Problemas de usabilidad en móviles

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#161]
En móviles Android (4.2.2, Chrome), el selectpicker da muchos problemas. Investigar si la versión para móviles puede ser más usable.

**Comment by PaulJBis** [comment]
A la espera de pruebas en varios modelos de móviles Android.

**Comment by sirym** [comment]
Ni en firefox ni chrome para android me da  problemas

**Comment by PaulJBis** [comment]
En mi tablet Samsung Galaxy Tab 2, con Android 4.0, ya no da problemas.
