### ISSUE TITLE
Problema con precios al editar un pedido existente

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#162]
Creamos un pedido con varias etapas (ejemplo: CFWQZWA8). Procedemos a editar las etapas, añadiendo bultos en un lado, quitando en otro… y al guardar los cambios, nos aparecen los errores:

Notice: Undefined offset: 4 in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 1292
Notice: Undefined offset: 4 in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 1292
Notice: Undefined offset: 1 in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 1292
Notice: Undefined offset: 1 in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 1292
Notice: Undefined offset: 1 in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 1488

**Comment by sirym** [comment]
Corregido
