### ISSUE TITLE
Bugs varios con cálculo de precios

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#164]
Ejemplo: pedido nº  CFGNKHU1
El pedido actual tiene 2 bultos para las 4 etapas. Si hacemos que 2 de las etapas tengan sólo un bulto y 2 etapas tengan 2 bultos, los precios para las 2 etapas con 2 bultos no se calculan bien (les aplica el precio de "1 etapa".

Puesto que seguramente habrá más bugs de este tipo, los iré recopilando aquí, en un solo bug,

**Comment by PaulJBis** [comment]
Ejemplo: pedido CFMX6RXH.

Este pedido tiene actualmente 10 etapas, 4 con 6 bultos y el resto con un bulto. Si borramos todas las etapas de 6 bultos excepto una, la etapa que queda (con 6 bultos) no se calcula con el precio correcto.

**Comment by PaulJBis** [comment]
Añadido al bug anterior: en general, si borramos etapas, las que quedan se calculan sin tener en cuenta el nº nuevo de etapas.

**Comment by PaulJBis** [comment]
Añadido al bug anterior: al final, si confirmamos la modificación del pedido, los precios sí se calculan correctamente. Lo que ocurre es que en la página que pide confirmación no salen los precios bien (salen los precios antiguos).

**Comment by sirym** [comment]
Ya se donde esta el error. Es con el estado cancelado. Mañana a primera hora esta arreglado

**Comment by PaulJBis** [comment]
Cerrado por el momento.
