### ISSUE TITLE
Portada:demasiado espacio tras cabecera

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#166]
Con los cambios de CSS de la nueva portada, ahora hay demasiado espacio después de la cabecera, al llegar a los elementos de la página.

**Comment by sirym** [comment]
A mi no me pasa en ningun ordenador ni navegador, recarga cache del css, puede ser eso

**Comment by PaulJBis** [comment]
Sigue pasando en otro navegador distinto al que uso habitualmente, con la caché borrada.
