### ISSUE TITLE
Al modificar o borrar pedidos, aparece "Undefined offset" y las fechas no se guardan bien

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#167]
Siendo un usuario registrado, al modificar o borrar un pedido, aparece el siguiente error:

Notice: Undefined offset: 2 in /homepages/15/d479577957/htdocs/caminofacil/app/modules/pedido.class.php on line 382

Notice: Undefined offset: 1 in /homepages/15/d479577957/htdocs/caminofacil/app/modules/pedido.class.php on line 382

Además, al modificar un pedido, la fecha se queda en 1-enero-1970.

**Comment by sirym** [comment]
Corregido
