### ISSUE TITLE
El email de confirmación de pedido se manda siempre en español

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#171]
¿Qué ocurre?

**Comment by sirym** [comment]
este email se envía desde la comunicación que hace el tpv hacia la pagina para la confirmación, no teniendo ninguna información este proceso sobre el lenguaje, voy a comprobar de que manera puedo tener esa información

**Comment by PaulJBis** [comment]
El TPV, en la información que envía de vuelta, sí manda un campo con el idioma. Mira la documentación.

**Comment by sirym** [comment]
Ya esta terminado.
