### ISSUE TITLE
En la página de cliente, los envíos de cada pedido salen repetidos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#174]
En la página de cliente, al pulsar sobre el enlace de "Modificar pedido", los envíos de cada pedido salen repetidos varias veces.

ESTE ES UN BUG QUE ESTÁ AHORA MISMO EN PRODUCCIÓN.

**Comment by sirym** [comment]
debe haberse creado al fusionar ramas, lo reviso

**Comment by sirym** [comment]
corregido

**Comment by PaulJBis** [comment]
Mensajes de error varios al entrar en la cuenta de usuario.
