### ISSUE TITLE
Recuperacion de contraseñas: el sistema permite enviar emails a usuarios no registrados

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#176]
Si un usuario no está registrado como cliente pero su email sí sale en la base de datos, el sistema permite enviarle un enlace para recuperar su contraseña.

**Comment by sirym** [comment]
Corregido

**Comment by PaulJBis** [comment]
Se vuelve a abrir, porque los tests que se han hecho hoy no han servido de nada. Ha cambiado el código.
