### ISSUE TITLE
Si un usuario que ya tiene su email en la BD se registra, no se le manda el email de registro

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#178]
Se supone que, si un usuario ha hecho pedidos antes pero no se ha registrado, su email se guarda en la base de datos, y si en un momento se registra, tiene que poder hacerlo, y pasa a aparecer como "usuario registrado".

Esto NO sucede. Si un usuario intenta registrarse usando un email que ya ha usado antes para hacer un pedido, no se le envía el email de registro.

Este es un tema que ya se había tenido en cuenta durante la fase de programación, y se había probado hasta conseguir que funcionara correctamente, pero ahora, en la web en producción, ha dejado de funcionar.

**Comment by sirym** [comment]
Corrregido

**Comment by PaulJBis** [comment]
Funciona si el usuario se registra en la página de registro, pero no si lo hace por 2º vez al hacer la compra.

**Comment by sirym** [comment]
Ahora si, verifica que te sale todo bien y cierra

**Comment by PaulJBis** [comment]
Se vuelve a abrir, porque los tests que se han hecho hoy no han servido de nada. Ha cambiado el código.
