### ISSUE TITLE
Cuando alguien se registra con una dirección de email ya registrada, no aparece error

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#179]
Si uno se registra (a través de la página de registro) con una dirección de email que ya está registrada, el programa no le muestra ningún mensaje de error. No envía el email de activación, pero el mensaje que sale es "Registro exitoso".

Lo mismo pasa cuando uno se registra mientras está pagando un pedido. No envía el email de activación, pero tampoco sale ninguna advertencia.

**Comment by sirym** [comment]
corregido
