### ISSUE TITLE
Comportamiento cuando hay etapas con datos duplicados

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#182]
Ahora mismo, si dos etapas tienen la misma fecha / pueblo de salida / llegada, se marcan en rojo, lo que está bien. Pero sólo aparece el mensaje de error cuando se pulsa el botón de "Cerrar pedido".

Idealmente, no debería ni aparecer dicho botón si hay datos erróneos. En su lugar, aparecería un mensaje en rojo como el que hay ahora cuando una etapa es doble. (El botón de "Cerrar pedido" no debería salir deshabilitado, ya que hay navegadores en los que el Javascript va lento y el usuario podría hacer click en él a pesar de todo; simplemente, no debería ni salir).

**Comment by sirym** [comment]
Hecho

**Comment by PaulJBis** [comment]
Si añadimos una etapa duplicada pero pulsamos el botón de "Cerrar pedido" (en vez del de "Añadir etapas), nos manda a una pantalla con un mensaje de error y nos redirige luego otra vez al formulario. ¿Seria posible que no  saliera la pantalla con el mensaje de error? ¿Que nos mandara directamente al formulario otra vez?
