### ISSUE TITLE
"Undefined index" al borrar un carrito en portada

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#183]
Usuario no registrado, al borrar un pedido en la portada:

    Notice: Undefined index: email in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 335
    Warning: Cannot modify header information - headers already sent by (output started at /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php:335) in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 2546

**Comment by sirym** [comment]
Parece que ya no ocurre este bug
