### ISSUE TITLE
Después de que un usuario "cierre" un pedido, debería poder añadir más etapas

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#184]
Ahora mismo, una vez que un usuario pulsa en "Finalizar el pedido" y llega a la página de datos, sólo puede modificar o eliminar etapas. ¿Qué pasa si lo que se le ha olvidado es añadir una etapa más? Debería haber un botón para permitirle añadir más etapas.

**Comment by sirym** [comment]
Añadido
