### ISSUE TITLE
Cuando se añaden etapas que no están en orden cronológico, aparecen desordenadas 

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#185]
Si añadimos una etapa que está antes de las demás (antes de la primera, por ejemplo), no aparece en el orden correcto. Las etapas deberían ordenarse por orden cronológico por sí mismas.

**Comment by sirym** [comment]
Hecho

**Comment by PaulJBis** [comment]
Sigue pasando. Si añadimos una etapa que está antes de las existentes, nos la añade al final, en vez de en su lugar correspondiente.

**Comment by sirym** [comment]
parece que ya si, @PaulJBis  confírmamelo si puedes
