### ISSUE TITLE
Mejoras de usabilidad al cargar los datos por defecto de la siguiente etapa

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#186]
Algunas mejorar del comportamiento del formulario para añadir etapas:

-En portada, si hay un pedido ya hecho, por defecto el formulario debería cargarse con los datos de la sig. etapa a la última: fecha, pueblo...
-A la hora de editar pedidos, si editamos una etapa, al guardar ésta el formulario debería cargarse con los datos siguientes a la última etapa del pedido. Ahora mismo carga los datos del día siguiente al que hemos editado, lo que no tiene mucho sentido.

**Comment by sirym** [comment]
Corregido

**Comment by PaulJBis** [comment]
Al entrar en la portada con un pedido ya hecho, el formulario no se inicializa con los datos de la última etapa.

**Comment by sirym** [comment]
hecho
