### ISSUE TITLE
Añadir enlace para "Modificar mi pedido" en la última etapa del checkout

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#187]
En la última página del checkout, justo antes de ir al TPV, debería haber también un enlace que nos permitiera modificar mi pedido.

**Comment by sirym** [comment]
hecho

**Comment by PaulJBis** [comment]
Los botones están bien, pero ocupan demasiado sitio. Lo ideal sería simplemente 2 enlaces de texto, como los que había antes.
(¿Esto hace que el UI sea inconsistente? Puede, pero la presentación de las etapas en portada también es inconsistente con el resto; de lo que se trata ahí, en la portada, es de minimizar el espacio que ocupa).
