### ISSUE TITLE
Portada: debería haber también un enlace de "Modificar"

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#188]
En la portada, junto al enlace de "Finalizar este pedido", debería haber también otro de "Modificar".

**Comment by PaulJBis** [comment]
Este enlace debería tener el mismo comportamiento que el de "Quiero modificar mi pedido", cuando el usuario ya ha hecho checkout.

**Comment by sirym** [comment]
hecho

**Comment by PaulJBis** [comment]
Los botones están bien y quedan bonitos, pero ocupan demasiado sitio. De lo que se trata en la portada es de minimizar el espacio ocupado. Lo ideal sería que fueran simplemente 2 enlaces de texto como el que había antes.

**Comment by sirym** [comment]
Ok
