### ISSUE TITLE
Admin.: en la página de pedidos, deben aparecer resaltados los problemáticos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#19]
Al entrar en la página de pedidos, deben aparecer en primer lugar, y resaltados de algún modo, aquellos que:

*No estén confirmados (por ser una etapa demasiado larga).
*No tengan un repartidor asignado.

**Comment by sirym** [comment]
Ahora aparecen resaltados en rojo los pedidos con estado pendiente (he creado 3 estados ¿provisionales?: pendiente, pagado, entregado) y los pedidos que no tienen un repartidor asignado.
