### ISSUE TITLE
Los nº de teléfono a veces se quedan cortados

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#190]
Al almacenar nºs de teléfono, sobre todo extranjeros, hay veces que se quedan cortados. Investigar por qué pasa esto: ¿meten los clientes espacios de más? ¿Caracteres de más?

Ver solución: ¿ampliar el campo en la DB? ¿O filtrar caracteres no deseados?

**Comment by sirym** [comment]
Ya hay una regla que comprueba que el número sea válido, el caso puede ser que se quede corto de algún país, se puede ampliar el campo.

**Comment by sirym** [comment]
Ampliado el campo a 16 chars, no debería haber ninguno superior.
