### ISSUE TITLE
No se pueden limpiar parcialmente los parámetros de búsqueda

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#194]
Supongamos que hacemos una búsqueda en la que hemos puesto fecha, repartidor, etc..., pero luego queremos hacer la misma búsqueda sin alguno de esos parámetros. ¿Cómo se puede "resetear" el desplegable de cliente y repartidor para que no tengan ningún valor? ¿Cómo podemos borrar alguna de las fechas, una vez que la hemos introducido? Ahora mismo, el botón "Limpiar" obliga a limpiar todos los parámetros de búsqueda.

**Comment by sirym** [comment]
He modificado los select para poder seleccionar un valor vacío y las fechas para poder borrar manualmente los campos
