### ISSUE TITLE
Los códigos QR no tienen información completa

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#197]
Lo único que sale en los códigos QR es la URL de la Web. No vamos a usarlos ahora, pero no estaría mal que fueran incorporando también la información de cada etapa (fecha, cliente...).

**Comment by sirym** [comment]
Solo se permite un valor en el código por lo que veo, por eso decidí añadir un url a la página del pedido

**Comment by PaulJBis** [comment]
Mejor entonces que sea un texto con la misma información que en la etiqueta.
