### ISSUE TITLE
Permitir que los enlaces de cabecera sean distintos según la página de la que se trate

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#199]
Ahora mismo, todas las páginas tienen que tener siempre la misma cabecera; algo tan sencillo como que cada página tenga un título distinto es imposible. Esto tiene efectos negativos, entre otras cosas, para SEO.

Reescribir el código para corregir esto. Idealmente, debería tener un sistema para poder generar enlaces a la misma página en la que estamos, pero en un idioma distinto (a fin de mejorar la navegación de las banderas).

**Comment by sirym** [comment]
Necesito tener esto más detallado. 
- Lo de generar enlaces en distinto idioma, ¿que sería? ¿tipo /contact, /kontakt, /contacto?
- Lo del title de cabecera sería ejemplo: Caminofacil - Página de contacto, Caminofacil - Nuevo pedido, etc?

**Comment by PaulJBis** [comment]
Lo del título es eso, sí.

En cuanto a lo de los enlaces, se trata simplemente de que, si estamos en alemán, el enlace sea "/de/contacto/".

**Comment by PaulJBis** [comment]
La parte de título de este bug todavía no está hecha. Ahora mismo, no hay forma de definir el título de una página estática desde el HTML de dicha página.

**Comment by PaulJBis** [comment]
Vale, ahora sí la hay.
