### ISSUE TITLE
Añadir un popup cuando el usuario selecciona una fecha en la que no hay servicio

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#203]
Si el usuario selecciona en el calendario una fecha en la que el servicio regular ya ha terminado, debe aparecer un aviso indicándolo, y diciendo que contacte con la empresa.

**Comment by sirym** [comment]
NOTA PARA DESARROLLAR:
las fechas nuevas desactivadas aparecen como class="day new disabled"
las fechas viejas desactivadas aparecen como class="day old disabled"
Tener en cuenta la de las nuevas para el popup
