### ISSUE TITLE
Fechas calendario: verificar que los límites están bien puestos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#206]
Ahora mismo, las fechas que hay en el archivo de config. son las de inicio y final de cada temporada, **ambas inclusive**. Verificar que el código respeta esto: ¿permite reservar en las dos fechas **ambas inclusive**?

**Comment by sirym** [comment]
Los días que deben indicarse en configuración es el día a partir del cual no se puede reservar y el último día no reservable para quedar deshabilitados en el calendario.
