### ISSUE TITLE
Las etiquetas deberían tener los comentarios de los usuarios

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#207]
En las etiquetas deberían salir impresos los comentarios de los usuarios. Es complicado, porque es texto libre y hay poco espacio, pero habrá que ver alguna forma.

**Comment by sirym** [comment]
ahora mismo en la version en desarrollo hay un ejemplo de como quedaría : http://caminofacil.sirym.com/index.php?section=home&node=pedido&action=print_tag&token=CFJ2B7Z0

**Comment by sirym** [comment]
Habría que limitar los caracteres a 250 o algo similar, para que no queden las etiquetas demasiado grande. En el ejemplo está con 250

**Comment by PaulJBis** [comment]
Tras revisar los comentarios que han estado escribiendo los usuarios en sus pedidos durante el último mes, he llegado a la conclusión de que esto no es realmente necesario, ya que muchas de esas notas son internas de Caminofácil (con lo que no debería verlas el usuario), o son detalles que se pueden comunicar de otra forma y quedan "raros" en una etiqueta (teléfonos de contacto, etc.).

En realidad, el único caso en el que haría falta de verdad seria si el usuario va a un hotel que no sale en la lista, y se ve obligado a aclararlo en el comentario, pero la solución a eso es mejorar la lista de hoteles.

Por tanto, cambiemos esto: si el usuario ha metido algún comentario, que aparezca tras la etiqueta un mensaje del tipo: "Consultar email para notas sobre este envio". Si el usuario no ha puesto nada, que no aparezca ningún mensaje.

**Comment by sirym** [comment]
Hecho
