### ISSUE TITLE
Las etiquetas de los pedidos antiguos no se generan

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#211]
En el servidor de pruebas, cuando se pulsa el enlace "Descargar etiquetas" para pedidos antiguos (en la página de usuario), la página de carga se queda esperando hasta 5 min., y no se generan nunca. Los pedidos nuevos, en cambio, se generan al momento.

¿Es esto un bug?

**Comment by PaulJBis** [comment]
También sucede en el servidor de producción.

**Comment by PaulJBis** [comment]
Pendiente: escribir un script para generar todos los PDFs de los pedidos antiguos que no se han generado aún. Deberían ser sólo los pedidos ya hechos, pero que todavía no se han servido, y de los que aún no se han generado PDFs.

**Comment by sirym** [comment]
Listo
