### ISSUE TITLE
Poder añadir más etapas desde la página de "Editar pedido completo"

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#215]
En la página de edición de pedidos, poner al final un botón para poder añadir más etapas a ese mismo pedido. De este modo cumplimos también la parte del presupuesto donde se decía:

"Posibilidad de ir guardando poco a poco las líneas de pedido, cuando se van añadiendo, para evitar que tras un posible fallo perdamos la información que hemos metido."

**Comment by PaulJBis** [comment]
Resulta confuso que aparezca el formulario de nueva etapa antes de las ya existentes. Sería mejor que apareciera después; de hecho, lo ideal es que por defecto estuviera oculta, y sólo apareciera cuando el usuario pulsa "Añadir más etapas".

**Comment by sirym** [comment]
Vale, ya está cambiado.
