### ISSUE TITLE
Añadir nuevas etapas en un pedido existente: la funcionalidad es incompleta

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#219]
En el formulario que sale para añadir nuevas etapas en un pedido ya existente:

  - No se selecciona automáticamente el repartidor cuando elegimos la localidad de comienzo de etapa.
  - Al elegir la localidad de comienzo, tampoco se selecciona automáticamente la siguiente localidad.

**Comment by sirym** [comment]
Hecho

**Comment by PaulJBis** [comment]
Fallo en la última versión en el git. Al añadir un pedido nuevo en la zona de admin., cuando guardamos el pedido:

    Notice: Undefined index: repartidor_1 in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 2878

    Notice: Undefined index: repartidor_2 in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 2878

    Notice: Undefined index: repartidor_3 in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 2878

    Warning: Cannot modify header information - headers already sent by (output started at /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php:2878) in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 3945

**Comment by sirym** [comment]
Revisado.
