### ISSUE TITLE
Clientes: al editar el pedido, no se pueden cambiar las fechas

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#22]
Cuando uno entra como cliente a editar un pedido, no puede cambiar sus fechas.

**Comment by sirym** [comment]
Acabo de hacer la prueba y si me va bien, la única fecha que no cambia es la de reserva, que es la fecha en la que el cliente ha realizado la reserva. Quizás debería quitar ese dato de la vista del cliente, ya que es un dato de referencia.

**Comment by PaulJBis** [comment]
Correcto. Le estaba pulsando en el sitio equivocado.
