### ISSUE TITLE
Añadir selectpicker a desplegable de hospedajes

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#222]
Añadir selectpicker a desplegable de hospedajes, para poder buscar éstos.

Dudas:

 - Esto, ¿era sólo para la página de admin., o para la del público también?
 - ¿Afectará al rendimiento?

**Comment by sirym** [comment]
Añadido en página pública

**Comment by sirym** [comment]
Añadido en página de administración

**Comment by PaulJBis** [comment]
Pero el selectpicker en la página de admin. no tiene buscador...
