### ISSUE TITLE
Selectpicker: permitir que busque sin tener en cuenta los acentos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#223]
Permitir que el selectpicker busque sin tener en cuenta acentos.

(Alberto ya ha mirado esto y dice que es muy complicado sin tocar el código del propio selectpicker. Se añade este bug por documentación, y también por si en el futuro se encuentra alguna otra forma).

**Comment by sirym** [comment]
Corregido

**Comment by PaulJBis** [comment]
Falta añadirlo en la sección privada también.

**Comment by sirym** [comment]
por algun motivo la opcion no funciona en los popup

**Comment by PaulJBis** [comment]
¿En qué popups? A mí me funciona con el de "Editar pedidos".

**Comment by sirym** [comment]
Sí, ya debe funcionar porque anoche subi la correccion de esto a pruebas, tengo que revisarlo de todas formas
