### ISSUE TITLE
Admin.: la fecha por defecto de un nuevo pedido debe ser mañana, no hoy

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#224]
Cuando añadimos un nuevo pedido, que la fecha por defecto del primer envío sea mañana, no hoy (pero sí se pueda seleccionar hoy también).

Este cambio nos lo piden porque, según dicen, muchas veces comienzan a dar de alta un pedido, pulsan en la fecha deprisa y sin fijarse y ese pedido sale dado de alta con la fecha de hoy, en vez de la del día siguiente.

**Comment by sirym** [comment]
Hecho

**Comment by PaulJBis** [comment]
El cliente llama quejándose de que ahora, en la búsqueda avanzada, las fechas salen por defecto con el día de mañana, en vez de vacías. ¿Puede tener que ver con este cambio?

**Comment by sirym** [comment]
Corregido
