### ISSUE TITLE
"Operación no autorizada" en el TPV al modificar un pedido

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#225]
Al hacer login e intentar modificar un pedido de forma que haya que pagar más, cuando vamos al TPV para pagar nos dice "Operación no autorizada".

**Comment by sirym** [comment]
No entiendo bien porque da el fallo. Creo que es porque el numero de pedido ya está registrado en el tpv como pagado o algo así, porque los datos se envian correctamente. Antes de hacer lo del carrito el sistema creaba un token provisional para las modificaciones y no daba este error.

**Comment by sirym** [comment]
corregido
