### ISSUE TITLE
Tras cancelar etapas, siguen apareciendo en las etiquetas a regenerar

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#226]
En la página de admin. entramos en un pedido, cancelamos etapas...

...Y las etapas canceladas siguen apareciendo en el listado, lo que puede estar bien, pero también aparecen en las etiquetas cuando las regeneramos.

**Comment by sirym** [comment]
Entonces la solucion que veo es añadir una excepcion a la consulta de las etiquetas
