### ISSUE TITLE
Errores al borrar etapas de un pedido

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#231]
El usuario hace un pedido. Luego, entra en su cuenta para cancelar una etapa y da este error:

Notice: Undefined variable: local1 in /homepages/15/d479577957/htdocs/caminofacil/app/controllers/account.php on line 676

Notice: Undefined variable: hosp1 in /homepages/15/d479577957/htdocs/caminofacil/app/controllers/account.php on line 678

Notice: Undefined variable: local2 in /homepages/15/d479577957/htdocs/caminofacil/app/controllers/account.php on line 682

Notice: Undefined variable: hosp2 in /homepages/15/d479577957/htdocs/caminofacil/app/controllers/account.php on line 684

Notice: Undefined variable: advertencia1 in /homepages/15/d479577957/htdocs/caminofacil/app/controllers/account.php on line 691

Warning: Cannot modify header information - headers already sent by (output started at /homepages/15/d479577957/htdocs/caminofacil/app/controllers/account.php:676) in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 76

**Comment by sirym** [comment]
Este error no me ocurre

**Comment by PaulJBis** [comment]
Sucede con algunas etapas; normalmente con la primera de cada viaje.

**Comment by sirym** [comment]
Era al cancelar una etapa que no conlleva devolucion. Corregido
