### ISSUE TITLE
Errores al entrar en la página de login

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#232]
Al entrar en la página de login:

Warning: include(/homepages/15/d479577957/htdocs/caminofacil/app/views/public/pagina/secciones/meta/meta_meta_meta.php): failed to open stream: No such file or directory in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 39

Warning: include(): Failed opening '/homepages/15/d479577957/htdocs/caminofacil/app/views/public/pagina/secciones/meta/meta_meta_meta.php' for inclusion (include_path='.:/usr/lib/php5.5') in /homepages/15/d479577957/htdocs/caminofacil/app/core/controller.php on line 39

**Comment by sirym** [comment]
Corregido
