### ISSUE TITLE
Errores al modificar un pedido

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#233]
Como cliente, entramos a editar un pedido que hemos hecho. Cancelamos una etapa y la etapa anterior la cambiamos para convertirla en etapa doble... y la etapa a borrar no se borra, sino que sigue saliendo en la lista.

**Comment by sirym** [comment]
Si la cantidad a devolver es 0 no tenía en cuenta si se había borrado una etapa o no. Corregido
