### ISSUE TITLE
Admin.: "Editar hospedajes" no funciona en AJAX

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#234]
LA función de "Editar hospedajes" no funciona si se la llama desde una ventana popup. Tampoco funciona en el framework actual.

(Baja prioridad).

**Comment by sirym** [comment]
¿Eso en que apartado está?

**Comment by PaulJBis** [comment]
En la sección "Editar hospedajes".

**Comment by sirym** [comment]
Corregido
