### ISSUE TITLE
Página de contacto no funciona

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#238]
Al enviar un email por la página de contacto:

Warning: require_once(app/modules/email.class.php): failed to open stream: No such file or directory in /homepages/15/d479577957/htdocs/caminofacil/app/controllers/contact.php on line 17

Fatal error: require_once(): Failed opening required 'app/modules/email.class.php' (include_path='.:/usr/lib/php5.5') in /homepages/15/d479577957/htdocs/caminofacil/app/controllers/contact.php on line 17

**Comment by sirym** [comment]
Corregido
