### ISSUE TITLE
Añadir idiomas a las URLS de la barra de navegación

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#248]
Hacer que todas las URLs de la barra de navegación sean de la forma "www.caminofacil.net/(idioma)/blablabla...

**Comment by PaulJBis** [comment]
Si entramos por defecto, sin poner ningún idioma, todas las páginas nos aparecen como "www.caminofacil.net/es/...". ¿Es esto bueno, desde el punto de vista de SEO? A consultar.

**Comment by PaulJBis** [comment]
Duda: si no hay ningún idioma en la URL, ¿de dónde saca la aplicación el idioma a usar?

**Comment by sirym** [comment]
Por defecto español, en caso de que la persona tenga ya una cookie con su idioma se carga en ese idioma

**Comment by PaulJBis** [comment]
Falta:

-Programar sistema para que los enlaces puedan estar en otros idiomas (traducidos: "/quienessomos/", etc.).

**Comment by PaulJBis** [comment]
Probado. De momento nos encontramos un bug: Al terminar un pedido, el enlace “Imprimir etiquetas” no funciona si estamos en un idioma distinto al español. (El enlace no tiene el idioma en la URL).

**Comment by PaulJBis** [comment]
Cuando estamos en un idioma que no es el español, no se puede entrar en la página de admin. ¿Es esto intencionado?

**Comment by PaulJBis** [comment]
Observación: el enlace para activar la cuenta cuando uno se registra no tiene el idioma en la URL. A pesar de ello funciona, pero... ¿sería conveniente añadirlo?

**Comment by PaulJBis** [comment]
El enlace de "Mi cuenta" en el correo de confirmación de los pedidos tampoco tiene idioma en la URL.

**Comment by sirym** [comment]
Hecho

**Comment by PaulJBis** [comment]
"Al terminar un pedido, el enlace “Imprimir etiquetas” no funciona si estamos en un idioma distinto al español. (El enlace no tiene el idioma en la URL)."

Esto sigue pasando, pero en el enlace que viene en el email de confirmación.

**Comment by PaulJBis** [comment]
"El enlace de "Mi cuenta" en el correo de confirmación de los pedidos tampoco tiene idioma en la URL."

Esto sigue pasando.

**Comment by PaulJBis** [comment]
Ojo: el bug #255 sigue pasando en esta rama (y probablemente todos los que se han arreglado en los últimos días también). A tener en cuenta a la hora de hacer el merge con master.

**Comment by sirym** [comment]
Corregidos los errores.

**Comment by PaulJBis** [comment]
Efectivamente, parece que todos los bugs mencionados aquí están ya resueltos. Faltan los que se arreglaron en la otra rama y no se han arreglado aquí (pendiente del merge).
