### ISSUE TITLE
Modificación de pedidos: añadir texto sobre devoluciones, gastos de gestión, etc.

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#25]
Cuando un usuario registrado quiere modificar un pedido, si éste implica una devolución o cobrarle de más, tienen que aparecer las pantallas correspondientes.

**Comment by PaulJBis** [comment]
La parte de modificación de pedidos está más o menos hecha. Falta la parte de borrado de pedidos.

**Comment by sirym** [comment]
No me había dado cuenta de que estaba abierto y he añadido otro para notificarlo. Ya está completado
