### ISSUE TITLE
Camino Portugués: al modificar las etapas de un pedido, no se cargan sus pueblos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#250]
Si hacemos un pedido del Camino Portugués y luego lo modificamos, al modificar una etapa no aparecen los pueblos del Camino Portugués, sólo los del Camino Francés.

**Comment by sirym** [comment]
Este error no me ocurre en las pruebas que estoy haciendo

**Comment by PaulJBis** [comment]
A mí me acaba de pasar. Hacemos un pedido, luego no lo completamos, sino que nos vamos a la portada, pulsamos "Modificar pedido" y cargamos una de las etapas. Salen los pueblos del Camino Francés.

**Comment by sirym** [comment]
Corregido
