### ISSUE TITLE
Admin.: en la página de "Editar pedidos", al añadir una etapa más, no se carga el hospedaje de destino

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#251]
En la página de admin., pulsamos "EDITAR" en un pedido. Luego añadimos una etapa nueva para ese pedido, y seleccionamos un pueblo de origen. Se nos carga automáticamente un pueblo de destino. Ahora intentamos cambiar éste... y los hospedajes no se cargan.

**Comment by sirym** [comment]
Corregido

**Comment by PaulJBis** [comment]
Subido ya a producción.
