### ISSUE TITLE
Admin.: fechas en buscador

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#254]
El buscador se ha modificado para que por defecto sólo busque los pedidos del año en curso.

Ahora mismo, los dos campos (inicio y final) tienen como fecha el 1 de enero, así que la búsqueda por defecto sólo saca los pedidos del 1 de enero. Habría que modificarlo para mejorarlo, probablemente haciendo que la fecha final por defecto sea 31 Dic. (o dejándolo vacío... pero ahora mismo, si uno de los campos de fecha está vacío, el buscador no encuentra nada).

**Comment by PaulJBis** [comment]
Actualmente, si sólo ponemos una fecha en el buscador, nos busca sólo EN esa fecha (no "desde" o "hasta" esa fecha).

**Comment by PaulJBis** [comment]
Se ha hablado con el cliente. Hay que dejar el buscador como antes, es decir, deshacer este cambio.

**Comment by sirym** [comment]
Hecho
