### ISSUE TITLE
Al editar un pedido, no se cargan los hospedajes si se cambia el pueblo de destino

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#255]
Hacemos un pedido, y luego, una vez pagado, entramos con nuestro usuario y lo modificamos. En el popup, al modificar el pueblo de destino, no se refrescan los hospedajes con los del nuevo pueblo elegido.

(¿No se había resuelto este bug varias veces ya? ¿Qué está pasando?)

Relacionado: bug #241 . Parecía que se había resuelto, pero es más que probable que tampoco esté funcionando ahora.

**Comment by sirym** [comment]
Corregido
