### ISSUE TITLE
Al editar un pedido ya hecho, nos vuelve a aparecer en el carrito de compra

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#256]
Entramos como usuario registrado, modificamos un pedido (sin tener que pasar por el TPV) y lo guardamos. Al volver a portada, el pedido aparece en nuestro carrito de compra.

Si pasamos por el TPV para pagar de más no sucede, pero si nos tienen que devolver dinero sí sucede también.

**Comment by sirym** [comment]
Corregido
