### ISSUE TITLE
Idiomas en URLs: ¿no tenerlas en cuenta para las etiquetas?

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#257]
¿Sería muy complicado programar la página de etiquetas para que no tenga en cuenta el idioma?

Imaginemos: un usuario hace un pedido y luego, desde un ordenador distinto con un idioma distinto al que usó originalmente, abre el correo de confirmación y pulsa en el enlace de las etiquetas. Tal como está ahora, si ese idioma es distinto al que se usó para hacer el pedido original, el sistema no le deja bajárselas.

**Comment by sirym** [comment]
Añadiendo el enlace con el idioma como está ahora mismo se soluciona el problema.
