### ISSUE TITLE
Admin: que el administrador pueda resetear la contraseña de los usuarios registrados

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#26]
"He perdido la contraseña. ¿No me la podéis cambiar?" Etc., etc.
Baja prioridad; hacer después de completar otras cosas.

**Comment by PaulJBis** [comment]
Ya no es de baja prioridad, porque ha habido clientes que se han quejado de ello.

**Comment by sirym** [comment]
El sistema que se ha hecho es para que el propio usuario pueda solicitar una nueva contraseña, no se si esto queda obsoleto con el otro método

**Comment by PaulJBis** [comment]
¿Qué otro método? Este es el único sistema viable, de todas formas, porque la contraseña está cifrada en la BD, así que no podríamos darles a los usuarios su contraseña original aunque quisiéramos.

**Comment by sirym** [comment]
A ver, me refiero a que el sistema que he desarrollado es el tipico: he olvidado mi contraseña
y se envía un email con una direccion unica para que el usuario pueda poner una nueva contraseña que sustituye a la anterior automaticamente.

**Comment by sirym** [comment]
¿Esto aún tiene alguna utilidad?

**Comment by PaulJBis** [comment]
En realidad, sería útil que el admin. pudiera resetear también desde el panel de control las contraseñas, pero tiene baja prioridad, así que lo cerramos de momento.
