### ISSUE TITLE
Trazabilidad: añadir estadísticas

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#266]
Además de lo ya hecho, el cliente pide poder hacer búsquedas según el origen del pedido.

En otras palabras, al buscador del principio habría que añadir un apartado con los posibles orígenes de cada envío: Web, admin,, repartidor... Habría que sacar las estadísticas sólo según el origen (quién metió el pedido por primera vez), no las modificaciones.

**Comment by albertoeps** [comment]
Los pedidos en la base de datos también tienen su id numérica autoincremental, se podría usar esto sin problemas.

**Comment by albertoeps** [comment]
Con estadísticas a que te refieres? A que aparezca una columna más de "Origen" simplemente? Y que al filtrar por origen salga el total de este origen, no?

**Comment by PaulJBis** [comment]
Sí.

**Comment by albertoeps** [comment]
Estaba preparándolo pero debido a limitaciones no es posible hacer bien una consulta con subquery y limite a la vez https://mariadb.com/kb/en/mariadb/subquery-limitations/ así que me veo obligado a añadir una columna a la tabla de envios con su origen.

**Comment by albertoeps** [comment]
Hecho :smirk_cat:

**Comment by PaulJBis** [comment]
En los posibles orígenes de cada pedido, no poner "cliente". Poner en su lugar "Web" (porque entiendo que esos son los pedidos que vienen de Internet, ¿no?)

**Comment by albertoeps** [comment]
Ok, Hecho
