### ISSUE TITLE
ID de pedido: hacerlo más sencillo

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#267]
El cliente se queja de que los IDs de pedido actuales (CFSDJFD1) son demasiado difíciles de recordar. Quiere que estén más basados en números.

Posible sugerencia adicional: que el comienzo de los IDs sea distinto según si el pedido viene de Web o de un admin.

**Comment by albertoeps** [comment]
Los pedidos en la base de datos también tienen su id numérica autoincremental, se podría usar esto sin problemas.

**Comment by PaulJBis** [comment]
No, mejor no. Si los números se autoincrementan, sería fácil para un atacante adivinar cuál va a ser el número del siguiente pedido. No me gusta.

Mejor hacer algo similar a lo de ahora, pero con menos letras y más números.

**Comment by albertoeps** [comment]
Ok, entonces lo que se puede hacer es cambiar el algoritmo que genera este token y que los pedidos nuevos lleven el que se desarrolle ahora

**Comment by albertoeps** [comment]
Se cambiará el formato a CF123456, está bien así?

**Comment by albertoeps** [comment]
Daría para 1000000 de pedidos 10⁶

**Comment by PaulJBis** [comment]
Mejor meter un par de letras al azar, para que haya más combinaciones. No demasiadas. Lo ideal sería:

CF - (4 o 5 cifras) - (2 o 1 letra).

**Comment by albertoeps** [comment]
Lo he puesto así: CF8947ZA 4 cifras y 2 letras
