### ISSUE TITLE
Admin.: en la Web de pruebas se ven todos los pedidos, incluso los del año pasado

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#269]
En la Web de pruebas, al entrar en la página de admin., se ven todos los pedidos de la BD, incluso los de hace años. También pasa con la web de repartidores.

Esto es muy molesto a la hora de ver los pedidos nuevos que hemos introducido, probar, etc., aparte de que en la web de producción no pasa.

**Comment by albertoeps** [comment]
Como he tenido que tocar las consultas de pedidos quizás haya tocado eso, lo reviso.

**Comment by albertoeps** [comment]
Corregido
