### ISSUE TITLE
Admin.: al añadir múltiples pedidos, da error en el 2º pedido

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#27]
En la pantalla de admin., al añadir múltiples pedidos, da error en el 2º pedido: el campo "nº de paquetes" se marca en rojo. Si intentamos meter un nº a mano, nos lo permite, pero el botón "Añadir" permanece en gris y no nos permite añadir todos los pedidos.

Todo esto en Firefox.

**Comment by sirym** [comment]
En google chrome hay un bug similar, pero con el estado del pedido. Tengo que revisar bien el código.

**Comment by sirym** [comment]
Un bug corregido, falta el otro

**Comment by sirym** [comment]
Segundo bug corregido

**Comment by PaulJBis** [comment]
Al añadir varios pedidos, aparece el error "Error al añadir pedido nº..:". Por ejemplo, si añadimos 2 pedidos, aparece "Error al añadir pedido nº 3"; si añadimos 3 pedidos, dice "Error al añadir pedido nº 4". Etc.

**Comment by sirym** [comment]
OK, corregido

**Comment by PaulJBis** [comment]
Sigue sucediendo, con el código del servidor.

**Comment by sirym** [comment]
Corregido
