### ISSUE TITLE
Mejorar sistema de login de repartidores

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#270]
- Ahora mismo, no hay botón de logout para los repartidores.
- Al depender de una tabla de DB distinta a la de los admins, es posible estar logueado como admin. y como repartidor a la vez. No me gusta ese diseño: es confuso.

**Comment by albertoeps** [comment]
Añado el botón de logout y que al loguearse con uno se desloguee con el otro?

**Comment by PaulJBis** [comment]
Debería haber un botón de logout en el sistema de repartidores, sí. ¿Dices de añadir también uno para admins?

**Comment by albertoeps** [comment]
Lo he añadido para repartidores y también que cuando se loguee un repartidor se desloguee el resto
