### ISSUE TITLE
Aclarar qué pedidos puede ver el repartidor en su panel

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#271]
En su panel de contro, ¿qué pedidos puede ver el repartidor? ¿Sólo los de mañana? ¿O los de toda la semana?

Aclarar con cliente.

**Comment by albertoeps** [comment]
De momento puse para ver los de el mismo día y los del día siguiente. Ya me dirás.

**Comment by PaulJBis** [comment]
Respuesta del cliente: sí puede verlo todo. Pongamos también para toda la semana.

**Comment by albertoeps** [comment]
Hecho
