### ISSUE TITLE
¿Puede el repartidor añadir pedidos multietapa?

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#272]
Ahora mismo, el repartidor debe añadir los pedidos etapa a etapa. ¿Puede añadirlos de varias etapas?

A consultar con cliente.

**Comment by albertoeps** [comment]
No puse añadir varias etapas por el echo de que se puede salir de la ruta del repartidor y no se muy bien como se puede controlar eso. Ya me dirás.

**Comment by PaulJBis** [comment]
Respuesta del cliente: sí, sí puede. Y si una etapa es de fuera de su zona, no puede añadirla (pero sólo por simplificar, no porque el cliente se oponga a ello).

**Comment by albertoeps** [comment]
Listo
