### ISSUE TITLE
Admin.: no se pueden editar pedidos completos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#273]
Al pulsar en el enlace de "EDITAR" un pedido completo, aparece:

Warning: Invalid argument supplied for foreach() in /var/www/vhosts/caminofacil.areadgn.com/httpdocs/app/controllers/administrador.php on line 256

Y el pedido está vacío.

**Comment by albertoeps** [comment]
Esto ya se arregló, se me olvidó ponerlo.
