### ISSUE TITLE
Pedidos no se guardan si el nombre del cliente tiene apóstrofes

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#275]
En la página de admin., si el nombre de cliente tiene apóstrofes (O'Reilly, etc.), los pedidos no se guardan.

Revisar TODO el código, ya que este parece un problema típico de escapar caracteres no válidos al construir la consulta SQL, así que lo más probable es que esté en muchas otras partes del programa.

**Comment by albertoeps** [comment]
Ya está corregido. El problema radicaba en la inserción en la base de datos del cliente. Se ha modificado la función mysqli por bind_params
