### ISSUE TITLE
Error con prepared statements en trazabilidad

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#276]
En el servidor de pruebas, en admin., al dar de alta un pedido nuevo, aparece el siguiente error:

Warning: Wrong parameter count for mysqli_stmt::bind_param() in /var/www/vhosts/caminofacil.areadgn.com/httpdocs/app/models/trazabilidad.class.php on line 41

**Comment by albertoeps** [comment]
Corregido
