### ISSUE TITLE
Los repartidores no pueden cancelar sus pedidos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#277]
Debería haber un botón para que los repartidores puedan cancelar sus pedidos. Según la especificación, debían poder hacerlo (aunque no borrarlos).

**Comment by albertoeps** [comment]
Vale, había entendido que simplemente era poder cambiar el estado a cancelado. Añado un botón entonces.

**Comment by PaulJBis** [comment]
No me había fijado que se podía cambiar el estado. De todas formas, un botón (el típico botón rojo) sería mejor para la usabilidad, sí.

**Comment by albertoeps** [comment]
Hecho

**Comment by PaulJBis** [comment]
Mejor que el botón esté abajo, junto con el de "Guardar cambios". Ya lo hago yo.
