### ISSUE TITLE
Mejorar barra de navegación para repartidores

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#278]
Añadir un botón de "Lista de pedidos" arriba, que enlace al listado de pedidos. De este modo, si están añadiendo un pedido nuevo y tienen que volver al listado, no dependen del botón "Atrás" del navegador.

**Comment by albertoeps** [comment]
Dándole al icono de caminofácil tienen esa opción

**Comment by PaulJBis** [comment]
Ya lo he hecho yo.
