### ISSUE TITLE
Admin: al pulsar sobre un pedido, aparece error en la ventana

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#279]
Al pulsar sobre cualquier pedido en la página de admin., sale esto:

Warning: Creating default object from empty value in /var/www/vhosts/caminofacil.areadgn.com/httpdocs/app/models/Envio/getPedido.php on line 197

Fatal error: Call to undefined method stdClass::get() in /var/www/vhosts/caminofacil.areadgn.com/httpdocs/app/models/Envio/getPedido.php on line 198
Guardar los cambios

**Comment by albertoeps** [comment]
Corregido
