### ISSUE TITLE
No se verifican los nºs de teléfono al hacer un pedido

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#28]
Decidir cómo hacer la verificación: ¿permitir números internacionales? ¿Sólo españoles? Consultar al cliente.

**Comment by sirym** [comment]
Ahora mismo lo que acabo de hacer es poner límite de 12 caracteres en los inputs, tengo entendido que es el número total contando el prefijo del país: +XX123456789.

**Comment by PaulJBis** [comment]
Según el cliente, les llaman clientes con todo tipo de nºs de teléfono, tanto españoles como extranjeros. Por tanto, habría que tener eso en cuenta.

**Comment by sirym** [comment]
Ya se verifican.
