### ISSUE TITLE
Admin.: no se generan las etiquetas

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#280]
Al crear un nuevo pedido en admin., las etiquetas no se generan. Pulsamos el botón de "Ver etiqueta" y se queda esperando. Si pulsamos "Regenerar etiqueta", aparece el error ya conocido:

Fatal error: Call to undefined method Etiqueta::load_public_message() in /var/www/vhosts/caminofacil.areadgn.com/httpdocs/app/models/etiqueta.class.php on line 65

**Comment by albertoeps** [comment]
#281 Corregido arreglando ese otro bug
