### ISSUE TITLE
Admin.: etiquetas generadas parcialmente

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#281]
En pedidos antiguos, creados antes de subir los últimos cambios, al pulsar "Ver etiqueta", se queda también esperando. Si pulsamos "Regenerar etiquetas", se generan, pero sólo 1 etapa, que no es necesariamente la primera.

**Comment by albertoeps** [comment]
Lo de que se queda esperando no es novedad, porque como no se ha generado anteriormente no tiene ningún archivo para cargar. Eso sí, este de que solo se genera de una etapa (por lo que veo es la última, como si sobreescribiese a las demás) me está mosqueando

**Comment by albertoeps** [comment]
Ya está arreglado. El problema era que la consulta de pedidos por defecto devolvía sólamente la etapa del día actual.
