### ISSUE TITLE
Google Conversion Tracking: ¿hace caso a los valores de config.php?

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#282]
En la web de pruebas, el parámetro GOOGLE_CONVERSION_TRACKING está como "false". A pesar de ello, al pagar aparece este mensaje:

Warning: include_once(): Failed opening 'google_conversion_tracking.html' for inclusion (include_path='.:/opt/plesk/php/5.6/share/pear') in /var/www/vhosts/caminofacil.areadgn.com/httpdocs/app/views/public/pagina/secciones/pago/pago.php on line 2

¿Está haciendo caso al parámetro?

**Comment by albertoeps** [comment]
Corregido
