### ISSUE TITLE
Admin.: no aparecen cambios en trazabilidad

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#285]
En admin., creamos un pedido. Luego editamos una etapa para cambiar el hospedaje. En la parte inferior, en "cambios", no aparece nada. ¿Es esto normal?

**Comment by albertoeps** [comment]
Parece ser que todo lo añadido de trazabilidad se perdió en el merge. Vuelvo a añadirlo

**Comment by albertoeps** [comment]
Corregido
