### ISSUE TITLE
Falta función  getNombreAdmin($id) en administrador.class.php

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#286]
En el merge, una de las funciones que aparecían en versiones anteriores del código, pero que ya no están, es `getNombreAdmin($id)`, en administrador.class.php.

Verificar: ¿seguro que no hace falta?

**Comment by PaulJBis** [comment]
¿En qué puede afectar esto, en la práctica? En el log de cambios que sale en el popup de cada envío; si esto causa algún bug, en dicho log de cambios el nombre del que hizo el cambio debería salir mal.

**Comment by albertoeps** [comment]
Esto funciona correctamente. Al final se ha hecho de otra manera con la función getDatosAdminByIdEl 1/5/2017 2:15, PaulJBis <notifications@github.com> escribió:¿En qué puede afectar esto, en la práctica? En el log de cambios que sale en el popup de cada envío; si esto causa algún bug, en dicho log de cambios el nombre del que hizo el cambio debería salir mal.
