### ISSUE TITLE
Falta un log en pedido.php

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#287]
En el commit 701c8cc92f6c2ecf1e03f1c61c1d6a40a883235a, se añade a pedido.php dos cambios. Uno de ellos se revierte luego (el de añadir `$log = new Trazabilidad_Model();`). Sin embargo, el otro, que es básicamente añadir el log de texto, no se ha revertido, y sin embargo no aparece en el archivo final.

En otras palabras, en el archivo final debería haber esta linea:

                            $this->write_log($_SERVER['HTTP_USER_AGENT'], "agent");

Pero no la hay. No hay ningún commit posterior en el que se haya borrado, por lo que sólo cabe la conclusion de que se haya borrado también en el merge, de algún modo.

**Comment by albertoeps** [comment]
Sí, parece ser que eso se perdió tambien, lo añado
