### ISSUE TITLE
Admin.: cuando los repartidores añaden un pedido, no se guarda su origen como "repartidor"

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#288]
Ahora mismo, hay algunos pedidos introducidos por repartidores que no aparecen en el buscador. Las circunstancias son:

-Hemos introducido esos pedidos (multietapa) como repartidor.
-En el buscador, ponemos el rango de fecha y elegimos "repartidor" como origen.
-Al buscar, sale la primera etapa de esos pedidos, pero no las siguientes, a pesar de que entran en el rango de fechas.

Ejemplos: CF5776AM, CF1679AF, CF9667DR

EDIT: hallada la causa. El problema es que, al añadir esos pedidos, no se guarda "repartidor" como su origen. Sólo se guarda cuando se edita el pedido.

**Comment by PaulJBis** [comment]
Hallada la causa. El problema es que, por alguna razón, esos pedidos no aparecen marcados con "repartidor" como origen.

**Comment by albertoeps** [comment]
Corregido
