### ISSUE TITLE
Admin.: buscador no funciona si no se ponen fechas

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#289]
En el buscador de pedidos, si no ponemos un rango de fechas, no aparece ningún pedido. Es decir: si solo buscamos por repartidor, cliente, etc., y dejamos las fechas en blanco, no nos encuentra los pedidos.

(Este es un bug que ya existía y que se arregló, pero ha vuelto a aparecer con los últimos cambios. En producción sí funciona bien).

**Comment by albertoeps** [comment]
Corregido
