### ISSUE TITLE
Sistema permite duplicar direcciones de email de usuarios

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#29]
El sistema permite duplicar direcciones de email de usuarios. Permite incluso registrarse varias veces con la misma dirección de email.

**Comment by sirym** [comment]
Ya está corregido, era un bug de validación al confundir usuarios registrados y usuarios que no se han registrado.

Ahora hace comprobación mediante contraseña, si no tiene contraseña no está registrado. Otra cosa es que haya activado la cuenta, eso se verifica en el login.

**Comment by PaulJBis** [comment]
En la tabla SQL, la columna "email" no está definida como UNIQUE, ni como PRIMARY KEY. ¿Es eso correcto?

**Comment by sirym** [comment]
Sí, debido a que el mismo cliente puede haber realizado un pedido anterior sin haberse registrado con el mismo e-mail.

**Comment by PaulJBis** [comment]
En ese caso, el sistema debería detectarlo y tenerlo en cuenta como un mismo usuario (no tiene sentido que una persona con la misma dirección de email sea tratada como dos usuarios distintos).

**Comment by sirym** [comment]
Ya está solucionado. Ahora al registrarse comprueba primero si hay un cliente con el mismo email y si ya existe lo unifica con este.

**Comment by sirym** [comment]
Corregido
