### ISSUE TITLE
Aparece el mensaje erróneo en el calendario de portada

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#291]
Como cliente, si vamos a la portada e intentamos elegir el día de mañana cuando se nos ha pasado ya la hora (cuando es después de las nueve), el mensaje que aparece en el popup es "Nuestro servicio regular sólo cubre del 15 de marzo...", lo cual está mal.

**Comment by albertoeps** [comment]
en las pruebas que he hecho no me aparece ningún popup

**Comment by PaulJBis** [comment]
Pasa sólo en inglés. En los demás idiomas no pasa.

**Comment by albertoeps** [comment]
En inglés el calendario tiene otro formato MM/DD/YYYY y el javascript estaba cogiendo la fecha marcada mal para el caso del mensaje.
