### ISSUE TITLE
Admin.: con Safari, no se puede entrar en la página de repartidores

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#293]
Al intentar entrar en /index.php?section=repartidor&node=login, aparece el mensaje:

   "Se han producido demasiados redireccionamientos al intentar abrir “‎URL/index.php?section=repartidor&amp;amp;node=login”. Esto ocurre cuando al abrir una página ésta le redirige a otra que, al abrirse, le redirige a otra página."

**Comment by albertoeps** [comment]
Revisa cache y cookiesEl 6/5/2017 19:48, PaulJBis <notifications@github.com> escribió:Al intentar entrar en /index.php?section=repartidor&node=login, aparece el mensaje:
"Se han producido demasiados redireccionamientos al intentar abrir “‎URL/index.php?section=repartidor&amp;node=login”. Esto ocurre cuando al abrir una página ésta le redirige a otra que, al abrirse, le redirige a otra página."

**Comment by albertoeps** [comment]
Esto sigue pasando?

**Comment by PaulJBis** [comment]
No lo sé. Hoy lo probaré.

**Comment by PaulJBis** [comment]
No, ya no pasa.
