### ISSUE TITLE
Admin.: No se pueden borrar pueblos de repartidores

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#295]
En la página de admin., si intentamos quitarle un pueblo a un repartidor, no nos deja.

Ejemplos: "Valcarlos". Está asignado a Taxi Monterroso y a Portuga Repartidor, y no podemos quitárselo.

**Comment by albertoeps** [comment]
Según veo si que se quitan en la base de datos, el error parece ser de otro tipo

**Comment by PaulJBis** [comment]
Pues cuando volvemos a la página de repartidores y entramos en la ficha de repartidor, vuelven a salir los pueblos que habíamos borrado.

**Comment by albertoeps** [comment]
Había un fallo al recorrer el array de pedidos asignados, la función tenía un bug. Esto estaba en producción desde siempre.

**Comment by PaulJBis** [comment]
No estaba en producción, porque lo he probado en producción antes de abrir el bug, y no pasa. Además, este año el cliente ha añadido nuevos repartidores, y se habría quejado si no hubiera funcionado bien.
Me preocupa que este arreglo no sea el correcto, y haya podido romper otra cosa. Habrá que probarlo.

**Comment by albertoeps** [comment]
He notado que en la base de datos los cambios se hacían correctamente y el fallo era al recorrer el array que mostramos en el popup (que marca como seleccionados los pueblos asignados). El funcionamiento de la página no depende de esta previsualización por lo que todo debería estar funcionando perfectamente incluso en producción.El 7/5/2017 2:13, PaulJBis <notifications@github.com> escribió:No estaba en producción, porque lo he probado en producción antes de abrir el bug, y no pasa. Además, este año el cliente ha añadido nuevos repartidores, y se habría quejado si no hubiera funcionado bien.
Me preocupa que este arreglo no sea el correcto, y haya podido romper otra cosa. Habrá que probarlo.

**Comment by PaulJBis** [comment]
Revisado código. Parece que el script modificado, getRepartidores.php, sólo es llamado desde la tabla de repartidores de admin., así que es improbable que afecte a otras partes del código.
