### ISSUE TITLE
Admin.: si cambiamos los datos de un pedido desde la página de editar pedidos globales, no queda registrada la causa en trazabilidad

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#297]
Si entramos en el enlace para editar un pedido de forma global, y cambiamos allí algún dato que afecte a todas las etapas (nº de bultos, etc.), al guardarlo, no aparece la razón en la lista de trazabilidad. Aparece la modificación, pero no aparece la palabra "modificado" al lado.

**Comment by albertoeps** [comment]
El fallo estaba que si recibia el estado en blanco, ahí lo metía en blanco. Corregido.
