### ISSUE TITLE
Admin.:  si sólo se modifican los datos de un pedido pero no su estado, aparece en el estado una entrada en blanco

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#298]
1) Vamos a la página de editar pedidos globales.
2) Editamos el nº de paquetes de todo el pedido.
3) Al guardarlo, en cada etapa nos aparece en el log 2 entradas: 1 entrada vacía y otra que pone "modificado".

**Comment by albertoeps** [comment]
Corregido.
