### ISSUE TITLE
Sistema permite crear envíos donde el pueblo de inicio y el final son el mismo

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#30]
Se pueden crear pedidos en los que el pueblo inicial y el final son el mismo.

**Comment by sirym** [comment]
Entonces solo debería mostrar los pueblos que hay a partir del primero marcado

**Comment by sirym** [comment]
Me acabo de dar cuenta que hay pueblos más allá de Santiago (sí, no me había dado cuenta), tienen distancia negativa, por lo que los pueblos que deberían mostrar al seleccionarlos deberían ser los anteriores. A ver si lo consigo.

**Comment by sirym** [comment]
Hay un bug en mysql. Al hacer la consulta "SELECT id, distanciaASantiago FROM pueblos WHERE distanciaASantiago < 774.1 LIMIT 1" me muestra como un resultado el pueblo que tiene de distanciaASantiago 774.1, cuando pido que sea menor (pasa con algunas distancias, no con todas).

**Comment by sirym** [comment]
Solucionado.
