### ISSUE TITLE
Admin.: en los pedidos del camino de Fisterra, la primera etapa no aparece, si empieza en Santiago

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#302]
Cuando hacemos un pedido del camino de Fisterra, si éste empieza en Santiago, la primera etapa no aparece en el listado de etapas de cada día. Tampoco sale en el listado que aparece tras pulsar "Añadir pedido". Sólo sale si pulsamos en la pantalla de "Editar pedido completo".

**Comment by PaulJBis** [comment]
Esto también pasa con los pedidos de la Web: la primera etapa no aparece.

**Comment by albertoeps** [comment]
Recuerdo que Santiago era un caso especial en cuanto a los caminos, reviso como funcionaba y lo corrijo.
