### ISSUE TITLE
Si editamos una etapa en "Editar pedido global" y no hay repartidor asignado, no sale en el log

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#304]
Similar a #299. Si editamos una etapa en "Editar pedido global" y no hay repartidor asignado al guardarla, no sale en el log.

La duda: ¿cómo es posible que nos deje guardar una etapa sin repartidor asignado? Esto ha sucedido, por ejemplo, cuando hemos cambiado el destino de una etapa. En esos casos, cuando con el nuevo destino no se asigna ningún repartidor, el sistema nos deja guardar la etapa... pero no guarda el cambio en el log.

**Comment by albertoeps** [comment]
Según veo al guardar los cambios aparece "Error al modificar el pedido", cosa lógica ya que no recibe ningún repartidor y por tanto, a pesar de que se actualicen varios campos no puede actualizar el de repartidor y no consigue llegar a la parte de trazabilidad. Hay que revisar porque el formulario nos deja hacer esto, cuando al editar la etapa en la tabla de pedidos normal no nos aparece lo de **Ningún repartidor**.

**Comment by albertoeps** [comment]
No solo ocurre en **Editar pedido global**, sino que en la tabla de pedidos si elegimos un pueblo de destino que no tenga repartidor asignado también ocurre. ¿Debería bloquearse completamente la modificación? ¿Qué sentido tiene entonces la opción _Ningún repartidor_? Si no recuerdo mal fue una opción que pidió el cliente.
Entonces de momento la corrección más lógica sería que no devolviese un error al guardar el pedido.

**Comment by albertoeps** [comment]
De momento ya inserta bien al trazabilidad y no muestra error al guardar.

**Comment by PaulJBis** [comment]
Efectivamente. Los pedidos pueden estar sin repartidor hasta que el cliente lo asigne, ya que puede ocurrir que necesite cambiar algún dato sin tener que decidir en ese mismo momento a qué repartidor dárselo. En cualquier caso, si un pedido no tiene repartidor, ya aparece en rojo en la lista.

**Comment by PaulJBis** [comment]
De momento ya no pasa.
