### ISSUE TITLE
Sistema de precios variables por etapas

### ISSUE THREAD

**Issue by albertoeps** [PaulJBis/Caminofacil#306]
IMPLEMENTACIÓN EN PRODUCCIÓN:
- [x] En la tabla pueblos añadir columna al final llamada 'tarifa'  de tipo int
- [x] En la tabla precios añadir columna al final llamada 'tarifa' de tipo int
- [x] Crear tabla llamada 'tarifas' con los campos: 'id(int)' y 'nombre(varchar 40)' (OJO: añadir a "id" AUTO_INCREMENT. Si no, no funcionará bien).
- [x] Vaciar tabla de 'carritos', ya que ha cambiado ligeramente el proceso de creación y puede ocasionar algún error.
- [x] Subir archivos a producción.

-------------------------------------------------------------------------------------------------------------------------------------
SISTEMA DE TARIFAS:
- [x] Añadir nueva tabla [tarifas:id,nombre] a la base de datos, columna 'tarifa' a pueblos, columna 'tarifa' a precios.
- [x] Implementar sistema en panel de Admin para gestionar precios y tarifas modificando el actual de precios.
- [x] Implementar sistema en parte pública: creación, modificación y cancelación de pedidos.

-------------------------------------------------------------------------------------------------------------------------------------
ORIGINAL:
La idea original es permitir en ciertas etapas un precio diferente, en principio para etapas del camino portugués, pero podría extenderse al resto para mayor flexibilidad.

En este momento el funcionamiento de cálculo de precio se realiza en función del número de etapas y de bultos totales de la contratación, por lo que al añadir este nuevo sistema se deberían **hacer dos cálculos** por separado: **uno para las etapas que no llevan este sistema y otro para las que sí lo llevan**.

Es necesario concretar además de esto si...
- [x] ¿Los precios de las etapas deberían definirse como punto de inicio y punto de fin afectando a todos los pueblos que se sitúan en medio? Ejemplo: Rubiaes-Redondela.
- [x] ¿El precio es variable en función del número de bultos?
- [ ] ¿Algún tipo de limitación aparte que debamos conocer?

**Comment by PaulJBis** [comment]
Yo creo que sería mejor generalizar el sistema de tarifas; en otras palabras, no pienses en términos de "etapas sin este sistema" y "etapas con este sistema", sino en términos de "¿qué tarifa le corresponde a esta etapa?"

Tal como lo había pensado yo, creo que lo mejor sería crear varios "packs" de tarifas. Por ejemplo:

*Pack 1:
-1 bulto, 1 etapa: 6 euros.
-1 bulto, 2 etapas o más: 5 euros.
-2 bultos, 1 etapa: 5 euros.
-Etc.

*Pack 2:
-1 bulto, 1 etapa: 7 euros.
-1 bulto, 2 etapas: 7 euros.
-Etc.

Y luego, a cada etapa se le asocia el "pack de tarifas" que le corresponde.

En cuanto a tus dudas:

1) Según me dice el cliente, el criterio para decidir qué tarifa usar es el pueblo de comienzo (porque en Portugal los transportistas son más caros, así que si un transporte comienza en Portugal, se tiene que cobrar con un precio mayor). Desde el punto de vista de la programación, supongo que asociaremos cada pueblo con un "pack de tarifas".

2) No lo sabemos aún, pero si usamos este sistema de "pack de tarifas" que te digo, no debería importar, porque en cualquier momento podríamos introducir una nueva tarifa en un pack determinado.

**Comment by PaulJBis** [comment]
Desde el punto de vista del SQL, se trataría de añadir una columna nueva a la tabla "precios", que se llamara "pack_tarifa" o algo así. Todas las tarifas que hay ahora mismo tendrían como valor "1"; luego añadiríamos otra tarifa, la del Camino Portugués, con el valor "2".

Y luego, añadiríamos otra tabla llamada "packs_tarifas", con:

ID: 1, 2...
Nombre: Estándar, Portugal...

Para que quede más claro de cada al usuario qué tarifa es cada cosa.

**Comment by PaulJBis** [comment]
Problema: la tarifa estándar no tiene forma de configurar sus pueblos, ni de modificarla.

Al intentar modificar los pueblos que corresponden a la tarifa del Camino Portugués, sale esto:

Warning: Missing argument 1 for Precio_Model::setTarifaPueblo(), called in /var/www/vhosts/caminofacil.areadgn.com/httpdocs/app/models/precio.class.php on line 194 and defined in /var/www/vhosts/caminofacil.areadgn.com/httpdocs/app/models/precio.class.php on line 201

Y al ver la tarifa de nuevo, ha guardado los datos al revés: ha conservado como pueblos que corresponden a esa tarifa justo los que habíamos desmarcado, y borrado los que habíamos marcado.

**Comment by PaulJBis** [comment]
Hay pueblos que corresponden al Camino Portugués, pero que no salen en el desplegable para editar pueblos de la página de precios. Concretamente: Matosinhos y Vitorino dos Piaes. 

Veo que se debe a que no tienen hospedajes listados. Sin embargo, creo que en este caso el desplegable sí debería sacar todos los pueblos que correspondan a un camino, aunque no haya hospedajes en él. Si se hace este cambio, ¿afecta a otras secciones de la página de admin.?

**Comment by PaulJBis** [comment]
Otra cosa: ¿hay alguna forma de eliminar una línea de una tarifa? Por ejemplo: supongamos que quiero borrar el "3 bultos o más" del Camino Portugués. ¿Cómo lo hago?

**Comment by PaulJBis** [comment]
Calcula mal los precios: elegimos "Ponte de Lima" a "Rubiaes", ambas con tarifas del Camino Portugués, y 2 bultos, y nos lo cobra como si fuera un bulto sólo.

**Comment by PaulJBis** [comment]
Otro cálculo erróneo:

![captura de pantalla 2017-08-22 a las 20 02 56](https://user-images.githubusercontent.com/7503165/29580075-04da37fe-8775-11e7-9be5-6d08470fecc9.png)

Tal como están ahora los precios, "1 bulto 1 etapa" debería ser siempre 8 euros, no 7.

**Comment by albertoeps** [comment]
Pero son dos etapas!

**Comment by PaulJBis** [comment]
Pero el precio, tal como lo tengo configurado, son "1 bulto 1 etapa" = 8 euros, y "2 a 3 bultos 1 etapa" = 7 euros. No tengo ningún precio ahora para "2 etapas".

**Comment by albertoeps** [comment]
Corregido todo

**Comment by PaulJBis** [comment]
-Al editar una tarifa ya existente y añadir un precio nuevo, me borra todos los demás que ya existían, y sólo me guarda el precio nuevo que se ha introducido.

-Al añadir una tarifa nueva, en el desplegable de pueblos siguen sin salir todos; sólo salen en el desplegable al editar una tarifa existente.

-¿Cómo se borra una línea de precios ya existente? Porque si es con la "X"  que aparece junto a cada precio en la página de "Editar precios", al pulsarla, me borra todos los precios de una tarifa.

Y estos fallos son sólo en la página de administración, sin haber probado siquiera si calcula bien los precios. Te agradecería que probaras las cosas en más detalle antes de darlas por entregadas.

**Comment by PaulJBis** [comment]
Los 3 bugs anteriores parecen ya resueltos.

**Comment by PaulJBis** [comment]
El sistema no detecta los casos de "2 o más etapas" cuando el camino se ha comenzado en otra zona. En otras palabras, si empezamos una ruta en Portugal (en donde hay otros precios), al llegar a Galicia (donde rigen los precios "normales") el sistema no detecta si llevamos X bultos durante 2 etapas o más en la parte gallega.

**Comment by PaulJBis** [comment]
Revisado en más profundidad: el sistema no detecta los casos de "2 o más etapas", punto. Tampoco los detecta en el Camino Francés.

**Comment by PaulJBis** [comment]
Se ha hablado con el cliente. Vamos a esperar a que nos mande la lista completa de precios del Camino Portugués, para saber cómo programar el sistema de precios.

**Comment by PaulJBis** [comment]
Los precios del Camino Portugués son:

1 bulto 1 etapa 7 euros
1 bulto 2 etapas 6.5 euros
2-4 bultos 6 euros
Más de 4 bultos 5.5 euros

**Comment by albertoeps** [comment]
Todos los ajustes y correcciones realizados.

**Comment by PaulJBis** [comment]
Al modificar un pedido ya hecho, si borramos todas las etapas y nos quedamos con solo una, no calcula bien el hecho de que el pedido tenga ahora sólo una etapa. Sigue poniendo el mismo precio descontado que si tuviéramos varias etapas.

Esto también pasa en el Camino Francés, así que probablemente es un bug que ya estaba de antes.

**Comment by PaulJBis** [comment]
Subido a producción. Dejamos esto abierto en previsión de nuevos bugs que irán surgiendo.
