### ISSUE TITLE
Migración Web a HTTPS

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#308]
Migrar la web entera para que use SSL. Necesario, ya que tenemos un formulario que pide contraseñas, y Google nos penaliza si no está cifrado.

**Comment by PaulJBis** [comment]
Guía sobre cómo migrar, desde el punto de vista de SEO:

http://searchengineland.com/http-https-seos-guide-securing-website-246940

**Comment by Raimond82** [comment]
Lo he subido al server de pruebas y parece que va bien.

Faltaría dar de alta la web con https en analytics, ya que hace el seguimiento por separado, y cambiar el blog para que también funcione con https.

**Comment by PaulJBis** [comment]
Respecto a Analytics y Webmaster Tools, Jesús tiene acceso a los dos desde su cuenta.

En cuanto al blog, ¿seguro que puede usar el mismo certificado digital? Está en otro subdominio, después de todo.

**Comment by PaulJBis** [comment]
Poner esto al final del .htaccess:

```
RewriteEngine On
RewriteCond %{SERVER_PORT} 80
RewriteRule ^(.*)$ https://caminofacil.net/$1 [R,L]
```

**Comment by PaulJBis** [comment]
Parece que funciona todo.
