### ISSUE TITLE
Hacer más eficiente el contador del nº de bultos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#309]
Ahora mismo, la página de admin. tiene, al principio de la tabla de envíos, un contador mostrando el nº total de paquetes y envíos en las fechas indicadas. Este contador se usa para ver cómo llevamos el año y para hacer estadísticas.

El problema es que, en este "use case", tenemos que hacer una búsqueda que requiera listar todos los envíos del año (1 enero - 31 diciembre), lo cual tarda muchísimo y recarga el sistema (no nos interesa el listado, sólo el nº total de bultos). Buscar alguna forma de mostrar esa información (nº de bultos y envíos en un períoodo de tiempo) sin tener que hacer una consulta que muestre todas las filas de la BD.

Importante: no sólo es un problema técnico (escribir la consulta SQL), sino también de UI. Pensar la forma de integrar esta nueva funcionalidad en la página de admin. existente para que sea fácil de usar.

**Comment by Raimond82** [comment]
La lentitud creo que no viene por el contador en sí, sino por el hecho de crear la tabla con miles de filas, teniendo que hacer varios join sobre 4 tablas diferentes. Hasta que el navegador la traduce completa no la muestra.

Una solución posible sería poner el total de pedidos tal como está y paginar los resultados de 50 en 50 o algo así, en caso de tener que mostrarlos. Eliminándolos nos quitamos una consulta a la bd bastante pesada.

Va a ser mucho más eficiente hacer un sum sobre el campo numBultos de la tabla envíos y contar el numero de registros relativos que tener que recorrerla entera, aunque sean dos llamadas a bd en lugar de una.

Y creo que sería mucho más útil ordenar los resultados por fecha DESC. Mostrar los útimos primero me parece de más utilidad evitando tener que desplazarse hasta abajo siempre. Esto tal vez unicamente al ver "Todos", en los de "Hoy" habría que evaluar según el número de pedidos del día.

Otra posibilidad es crear un cron a las 23:59 que haga recuento de envios de año, mes, semana, ayer,hoy etc.. y guardarlo en una nueva tabla para estadísticas o un archivo json, pudiendo de este modo mostrarlo incluso en la entrada al admin sin que se note mucho en eficiencia. Lógicamente no sería en tiempo 100% real. Mayor frecuencia en el cron sería posible si fuese realmente útil.

**Comment by PaulJBis** [comment]
Lo de la paginación es una idea interesante, pero no creo que sea prioritaria, porque en la práctica, nuestro cliente casi nunca va a sacar un listado con miles de pedidos. En la práctica, en el día a día nuestro cliente consulta los pedidos que hay para el día siguiente o (como mucho) para la semana, y no son nunca más de unos pocos cientos, con los que se maneja perfectamente.

En otras palabras: el hecho de que ahora mismo saque la tabla entera cada vez que queremos saber el nº total de pedidos es precisamente lo que queremos cambiar, ya que esa tabla no es necesaria. De lo que se trataría sería de crear otra página, o añadir otro formulario... lo que sea, pero que al ejecutarlo sólo ejecutara la consulta SQL con "SELECT SUM()...", tal como dices.

**Comment by PaulJBis** [comment]
Respecto a los cambios que se han hecho: ahora mismo está configurado para mostrar sólo los últimos 25 transportes. Ese nº (el "25") tiene que estar en config.php, como una constante que sea fácil de editar (imaginemos lo que pasaría si mañana el cliente quiere que salgan los 60 últimos pedidos...).

**Comment by PaulJBis** [comment]
Nota: ahora mismo, con el sistema actual, tarda 2:34 min. en sacar el nº de pedidos de un año.

**Comment by PaulJBis** [comment]
Con el cambio de "25" por la constante, ahora, al probarlo, no aparece la paginación. Lo he subido al servidor de producción para probarlo con la BD real y no aparece, y en el servidor de pruebas tampoco aparece. (???)

**Comment by Raimond82** [comment]
A mi en el de pruebas si que me aparece. Al darle a TODOS, que es en el único sitio donde se aplica la paginación

**Comment by PaulJBis** [comment]
Subido a producción.

**Comment by Raimond82** [comment]
He comprobado que efectivamente en el admin en producción el listado de pedidos va muy lento. Para sacar el listado de pedidos de la semana tarda casi 10 segundos.

El problema está en que para cada item listado, el sistema hace consulta a la bd para saber el nombre de pueblo de origen y destino, alojamientos, nombre de cliente y de repartidor, lo que multiplica el número de consultas.

Lo he modificado para que antes de sacar el listado cargue en arrays todos estos datos, así sólo es una consulta por listado, en lugar de una por item, y va mucho mejor.

En la consulta mysql de pedidos faltaban unas referencias a tabla, que aunque funcionaba igualmente es mejor ponerlas.

Lo he probado en desarrollo e incluso he hecho prueba en producción para probarlo con una cantidad mayor de pedidos. En producción después de probarlo he vuelto a dejar todo como estaba, así que vuelve a ser lento.

Subido al git en la rama admin_pedidos_lento

**Comment by PaulJBis** [comment]
Subido a producción.
