### ISSUE TITLE
Kms. que definen etapas están "hard-coded" en el código

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#31]
Los valores de 30 y 60 km., que se usan para definir los límites entre etapas, están metidos en el código, en vez de definidos como una variable en un archivo de config. externo. Si mañana el cliente quiere, por ejemplo, que cada etapa sean 40 km., habría que ir línea por línea en el código cambiando este dato en todos los sitios en que aparezca.

**Comment by sirym** [comment]
¿Serían dos valores, uno para una etapa y otro para dos etapas? O siempre sería un valor y para más etapas el doble (ejemplo: una etapa 40km, dos etapas 40x2=80km).

**Comment by PaulJBis** [comment]
El valor sería el de una etapa, en principio. A partir de ahí, el valor de la etapa doble es fácil de calcular.

**Comment by sirym** [comment]
Ya está solucionado. La variable para referirse a este valor es 'DIST_ETAPA'
