### ISSUE TITLE
Rediseño de etiquetas

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#317]
Cambiar algo el diseño de las etiquetas imprimibles que se generan a los usuarios. Las notas del cliente, de momento, han sido:

-Disminuir el tamaño del código QR, ya que en realidad no se utiliza.
-Mostrar tipo de alojamiento. Sobre esto: ahora mismo, en la DB, se guarda el tipo de alojamiento en una columna separada del nombre ("Hostal" "Central"), lo que genera este problema. El problema, claro, es que en muchos casos se ha añadido también el tipo de alojamiento en la columna de nombre ("Hostal" "Hostal Central").
-Logo Caminofácil algo más grande.
-Nombre del cliente algo más grande.

**Comment by Raimond82** [comment]
Subido diseño nuevo para etiquetas.

Hay que revisarlo y ver si vale así o si hay que hacer algún cambio.

**Comment by PaulJBis** [comment]
OJO: cuando hay una nota, en la etiqueta no aparece el texto de ésta, sino "Consultar email". La razón es que en la nota pueden aparecer direcciones de destino, datos personales...

**Comment by PaulJBis** [comment]
Subido a producción.
