### ISSUE TITLE
Admin.: cambios en el panel de repartidores

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#318]
En el panel de repartidores, hacer los siguientes cambios:

-Suprimir el botón "Todos".
-Añadir un botón "Mes", para ver los pedidos de los próximos 30 días.
-Añadir un buscador por fechas, para ver todos los pedidos que correspondan a ese repartidor durante unas fechas determinadas.

**Comment by PaulJBis** [comment]
Subido a producción. A la espera de la opinión del cliente.

**Comment by PaulJBis** [comment]
Se ha hablado con el cliente. Sólo una cosa más: el buscador de fechas debería permitir buscar sólo en el año en curso.

**Comment by Raimond82** [comment]
Limitándolo sólo al año en curso, el problema va a surgir al principio y final del año. Si estamos a 25 de diciembre sólo nos dejaría buscar del 25/12/2018 a 31/12/2018, y si estamos a día 01/01/2018 ya no nos dejaría consultar lo del día anterior.

Lo que puedo hacer es limitarlo entre hoy y dentro de 365 días, es decir, del  07/02/2018 a 07/02/2019 o incluso desde hace un mes hasta dentro de 365 días, por si tienen que consultar lo de los últimos días (07/01/2018 a 07/02/2019).

**Comment by PaulJBis** [comment]
Eso no es problema, porque en diciembre y enero los transportistas no trabajan. La temporada del Camino es normalmente de marzo a noviembre. Además, este cambio es sólo para los transportistas, no para el administrador, que sigue pudiendo acceder a todo.

**Comment by PaulJBis** [comment]
Hecho.
