### ISSUE TITLE
Política de privacidad y aviso legal

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#319]
Añadir textos de política de privacidad y aviso legal.

Ojo: tienen que estar en los cuatro idiomas.

**Comment by Raimond82** [comment]
Hecho. Faltaría editar los archivos con el contenido de cada sección.

Los links están en el footer, al lado de las cookies

**Comment by PaulJBis** [comment]
Vale. Esto es una cosa que sugirió Jesús (le he invitado a entrar en este repositorio como colaborador), y estoy a la espera de que él me dé los textos.

**Comment by PaulJBis** [comment]
Por hacer:

1) Merge con la rama principal.
2) Una vez hecho el merge, traducir las cadenas de texto nuevas que faltan.
3) Consultar con cliente sobre aviso legal.

**Comment by PaulJBis** [comment]
Ahora mismo, pide permiso cada vez que hacemos un pedido. Habría que mejorar eso, y guardar en BD el consentimiento.

**Comment by PaulJBis** [comment]
Guardado. Problema: si un usuario se registra mientras está haciendo un pedido, no se guarda el consentimiento.

**Comment by PaulJBis** [comment]
Solucionado. Queda subirlo a producción.

**Comment by PaulJBis** [comment]
Ya está.
