### ISSUE TITLE
public_information(): crear 2 mensajes de advertencia

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#32]
Necesito modificar controller.php para que, en public_information(), haya dos mensajes distintos de advertencia, con 2 textos distintos. (En otras palabras, que haya 2 variables: $advertencia1 y $advertencia2).
Una vez modificado el código, redactaré los 2 textos y modificaré la plantilla para ello.

**Comment by sirym** [comment]
Necesito saber a que evento corresponde cada advertencia para programarlo.

**Comment by PaulJBis** [comment]
Son del mismo evento (etapa de más de 30 kms.). Lo que pasa es que, al aparecer en dos partes distintas de la página, quiero que tengan textos distintos.

**Comment by sirym** [comment]
Si quieres pásame los textos por aquí y los añado, es que estoy modificando bastante el controller.php

**Comment by PaulJBis** [comment]
Texto 1: este recorrido se considerará como ETAPA DOBLE.
Texto 2: ATENCIÓN: al sobrepasar los 30 kms., este recorrido se considera como una etapa doble, por lo que se cobrará como dos etapas.

**Comment by PaulJBis** [comment]
Y eliminar la advertencia que aparece impresa en la parte superior de la página.

**Comment by sirym** [comment]
Corregido. Las dos variables nuevas son: $advertencia1 y $advertencia2
