### ISSUE TITLE
Espacio en blanco en la parte superior de la pantalla

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#323]
No aparece en la página principal, pero cuando empezamos a añadir etapas, en todas las páginas aparece un espacio en blanco arriba.

**Comment by kinti** [comment]
en https://caminofacil.areadgn.com no sucede...., mmmm, algo de progra?....., 
pasaba antes? Sigo mirando

**Comment by Raimond82** [comment]
Esto debería estar solucionado con el commit "Cambio menor. Desplazamiento superior en login y registro" de 24 de Enero. El fallo surgió al hacer la cabecera fija, porque las secciones no tienen el mismo contenedor.

**Comment by PaulJBis** [comment]
Ese commit es el bbf5fe99b5140. A comprobar si está en producción.

**Comment by PaulJBis** [comment]
Resuelto.
