### ISSUE TITLE
La base de datos no guardan qué repartidor es el que da de alta los pedidos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#326]
Tal como está ahora, el sistema guarda el origen de los pedidos: "web", "administrador" y "repartidor", pero no distingue qué repartidor es el que ha introducido cada pedido.

Sería necesario guardar también esa información.

**Comment by PaulJBis** [comment]
Distintas posibilidades:

-Guardar en "origen", las palabras "repartidor | (nombre de repartidor)".
-Crear una columna numérica aparte, con el ID del repartidor (o NULL si no lo ha metido ningún repartidor).

**Comment by Raimond82** [comment]
Probado y subido al git.

Hay que cambiar en la base de datos el campo 'origen' de la tabla 'envios' a varchar(255) para que guarde los nombres completos

**Comment by PaulJBis** [comment]
Subido a producción.
