### ISSUE TITLE
Hay pedidos que el TPV no cobra pero que se marcan en el sistema como pagados

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#327]
Ha habido 3 pedidos, CF4906CF,  CF6118QB y CF7975LM, que dan en el TPV "Comunicación online incorrecta", y que sin embargo aparecen en nuestra base de datos como pagados. WTF???

Detalles:

- Todos son del 13 de marzo.
- En el primer pedido (CF4906CF), los logs indican que nuestro servidor devolvió un error 500, pero en los otros dos, indican que nuestro servidor devolvió una respuesta correcta, a pesar de lo cual el TPV sigue indicando un ERR-001.
- En el primer caso, en nuestro log propio no aparece el paso "PEDIDO MARCADO PAGADO EN BASE DE DATOS", pero en los otros dos sí.

EDIT: hay otro pedido, del día 14, que es CF2860AM, al que también le pasa.

**Comment by PaulJBis** [comment]
Hoy hemos tenido que regenerar el certificado SSL de la Web, pero lo hemos hecho a una hora que no coincide con ninguno de los pedidos anteriores.

**Comment by PaulJBis** [comment]
Hipótesis: se debe a que, a veces, el sistema tarda demasiado en enviar el email de confirmación, y como el "OK" sólo se imprime después de enviar éste, el servidor de CECA da timeout. Se han añadido más logs para comprobar esto.

**Comment by PaulJBis** [comment]
CF4225RL
CF1042LE

**Comment by PaulJBis** [comment]
Se ha cambiado ya el orden de las acciones en pago.php, para que envíe el "OK" antes de enviar el email de confirmación.

Aun así, se ve en los logs que tarda casi 20 segundos a veces en guardar todas las etapas en la BD. Añadir más logs en pedido.class.php (insertPedido()), para ver dónde se va el tiempo.

**Comment by Raimond82** [comment]
No lo he probado pero se me ocurre esto:

En pago.php justo despues de mostrar el OKY, genera las etiquetas. Seguramente el problema venga por ahí, por el bug que hay de que no se generan las etiquetas, y hasta que no procesa todo no muestra el OKY.

Tiene un timeout de 2,5 por etiqueta, igual de ahí salen los 20 segundos.

Si quitando de ahí la generación de etiquetas funciona, ya sabemos que es de eso.

**Comment by PaulJBis** [comment]
Tras las últimas modificaciones, parece que no está volviendo a pasar.

**Comment by PaulJBis** [comment]
Cuellos de botella en el proceso de pago:

-Envío del email de confirmación.
-Generación de etiquetas.

Hay que hacer que ambas sean async.

Otra pregunta: ¿cuál es el timeout del servidor de CECA?

**Comment by PaulJBis** [comment]
Respuesta: el timeout del servidor de CECA es de 30 seg.

**Comment by PaulJBis** [comment]
Cerramos de momento, porque no parece que haya vuelto a pasar. Para una solución definitiva, véase bug #243 , sobre todo las notas sobre fastcgi_finish_request().
