### ISSUE TITLE
No permitir hacer pedidos de más de 2 etapas

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#33]
Acabo de hablar con el cliente, y por lo que me ha dicho, si un pedido es de más de dos etapas, debe aparecer directamente un mensaje indicándole que se ponga en contacto con Caminofacil. No debe permitirle crear el pedido, ni cobrarle, lógicamente.

**Comment by sirym** [comment]
Como yo lo tengo hecho ahora mismo el sistema detecta que hay más de dos etapas, avisa al cliente, no se le cobra y se registra el pedido como 'pendiente' en lugar de 'pagado'. En observaciones aparece directamente contactar con el cliente.

**Comment by sirym** [comment]
Todos los pedidos con estado 'pendiente' aparecen remarcados en rojo en la tabla de pedidos.

**Comment by PaulJBis** [comment]
El cliente dice que no se le permita ni crear el pedido. Que aparezcan directamente los datos de contacto de Caminofacil. De todas formas, hace un momento he hecho una prueba con un pedido de más de 60 km., y me ha aparecido el enlace a Paypal y, al entrar en él, incluso me ha intentado cobrar.

**Comment by sirym** [comment]
Sí, porque esa parte aún no está subida. ¿Lo modifico antes de subirlo?

**Comment by PaulJBis** [comment]
Sí, mejor.

**Comment by sirym** [comment]
Corregido
