### ISSUE TITLE
Hay pedidos que se hacen con los hospedajes equivocados

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#334]
Ejemplo de pedido que se ha hecho:

-La primera etapa, tal como aparece en el email de confirmación, va de Oporto a Vila Chá (Camino Portugués), pero el hospedaje que aparece es el "Camping Orbitur - Angeiras ", que no corresponde a Vilachá sino a Lavra/Matosinhos.

-Luego, cuando el administrador intenta cargar ese pedido, le aparece el campo de hospedaje vacío (lógicamente, ya que el dato no es válido).

¿Por qué se están corrompiendo esos datos?

(Relacionado con bug #332 , pero no basta con añadir validación extra. Habría que averiguar cómo es posible que se estén corrompiendo los datos aquí).

**Comment by PaulJBis** [comment]
En este caso, el id del hospedaje que ha salido mal ha sido 2085, el id del pueblo al que corresponde (Matosinhos) es 303, y el id de Vila Chá es 330.

**Comment by PaulJBis** [comment]
Averiguada la causa:

-Si elegimos "Oporto", el siguiente pueblo que sale es Matosinhos, y el hospedaje que sale automáticamente es "Camping Orbitur - Angeiras".
-Si cambiamos el pueblo de destino, el desplegable de hospedaje debería refrescarse automáticamente... pero si no lo hace, el valor que se queda es el del "Camping Orbitur - Angeiras".

Por tanto, la causa se debe simplemente a que el AJAX que refresca el desplegable de hospedaje ha dado timeout.

**Comment by Raimond82** [comment]
Corregido el js que carga los hospedajes. Estaban mal los id del desplegable de hospedajes de destino, y por eso no los ponía a 0 al cambiar de pueblo. Así al cargar un nuevo pueblo, si fallase el proceso de hospedajes, no habría ninguno seleccionado y no dejaría añadir la etapa.
