### ISSUE TITLE
Añadir un checkbox "He leído y acepto las condiciones de contratación"

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#35]
Antes de aceptar cada pedido, el usuario debería marcar un checkbox que diga "he leído y acepto las condiciones de contratación", con un enlace hacia una sección de la página estática.

**Comment by sirym** [comment]
¿A que pagina estática debería enlazar?

**Comment by PaulJBis** [comment]
No te preocupes de momento. Cuando esté hecha, te enviaré la URL.

**Comment by PaulJBis** [comment]
La URL es:

http://www.caminofacil.net/NEW/?section=home&node=comofunciona#terms_of_service

**Comment by sirym** [comment]
Ya está actualizado y subido
