### ISSUE TITLE
Modificar pedidos: no actualizar pueblo de destino automáticamente

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#36]
En la página de usuario, al editar un pedido existente, el sistema nos cambia automáticamente el pueblo de destino si cambiamos el pueblo de origen.

Este comportamiento está bien en la página pública, pero cuando un pedido ya está hecho, puede desconcertar a los usuarios e incluso moverles sin querer datos que no querían cambiar.

**Comment by sirym** [comment]
Corregido
