### ISSUE TITLE
Devoluciones: mejorar chequeo nº IBAN

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#39]
Si hacemos una modificación que implica una devolución, y metemos mal el nº de cuenta, aparece una página en blanco con solo un mensaje de error, y tenemos que reiniciar el proceso de nuevo.

Idealmente, debería aparecer el mensaje de error y la página con el formulario con el nº de cuenta de nuevo, para dar la oportunidad a volver a introducirlo.

**Comment by sirym** [comment]
Corregido
