### ISSUE TITLE
Usuarios no registrados: se deberían ir actualizando sus datos con los más recientes

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#45]
Un usuario hace un pedido y no se registra; después, hace otro pedido y tampoco se registra... pero pone un nombre o nº de teléfono distinto del de la primera vez. Sin embargo, los datos que añadió la primera vez se han quedado guardados ya en la BD, y son los que aparecen al administrador.

En esos casos, los datos que se guarden en la BD deberían ser los últimos que añada, es decir, los que añada en su pedido más reciente. En el momento en que se registre, como es lógico, la cosa cambia.

**Comment by sirym** [comment]
Hecho

**Comment by PaulJBis** [comment]
Vuelve a pasar.

**Comment by sirym** [comment]
Corregido
