### ISSUE TITLE
Añadir mensaje si un usuario registrado hace un pedido sin hacer login

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#47]
Si un usuario no ha hecho login y mete la dirección de email de un usuario ya
registrado, le permitimos tramitar el pedido... pero que aparezca un mensaje en algún
momento diciendo: "Tienes ya creada una cuenta con nosotros. Te recordamos que puedes entrar
para modificar y borrar tus pedidos tú mismo".

**Comment by sirym** [comment]
Añadido

**Comment by PaulJBis** [comment]
Acabo de probarlo. No aparece el mensaje.

**Comment by sirym** [comment]
Ese cambio lo he hecho despues de subir los cambios

**Comment by PaulJBis** [comment]
Visto.

**Comment by sirym** [comment]
Esto ya estaba corregido
