### ISSUE TITLE
Paypal prueba: errores al volver de la página

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#48]
A veces, al volver de la página de Paypal, aparece un error "Error, no hay ningún pedido pagado", a pesar de que el pago se realizó con éxito, el email se ha enviado y el envío se ha guardado bien.

No he conseguido reproducirlo de forma fiable aún, pero de momento lo dejo abierto para ir añadiendo más datos a medida que los tenga.

**Comment by sirym** [comment]
Todas las variables que se envian a paypal se borran despues de haber insertado el pedido y haber enviado el email para evitar que se vuelven a enviar por error si el usuario recarga la pagina. En ese caso aparece el mensaje que mencionas.

**Comment by sirym** [comment]
Puede que este problema se deba al tiempo de duracion de la sesion, depende de la configuración del hosting (php.ini). Si estás mucho tiempo sin tocar nada se borran. No se cuantos minutos está configurado.

**Comment by PaulJBis** [comment]
Al no usarse ya Paypal, cerramos este bug.
