### ISSUE TITLE
Chequeo de campos que faltan al hacer un pedido

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#5]
Ahora mismo, al hacer un pedido, si no se introduce alguno de los campos que faltan (teléfono, email...), nos da una pantalla en blanco que dice simplemente "Pedido no creado", o algo así. Mejorar ese apartado: que aparezca de nuevo el formulario con el campo que falta marcado, etc.

**Comment by sirym** [comment]
No me aparece este error al probarlo. Lo he probado tanto en chrome como en firefox.

**Comment by sirym** [comment]
Ya se ponen en rojo los campos que faltan, no he podido comprobar el error que mencionas, porque no me ha dado nunca. NOTA: Los campos de localidad y hospedaje no se iluminan en rojo porque utilizan un script propio que entra en conflicto con el otro. Debería crear un script aparte o cambiar al select tradicional sin busqueda.
