### ISSUE TITLE
Modificar pedidos: a veces aparece el mensaje "error al modificar el pedido"

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#50]
A veces, al modificar pedidos que no implican un cambio de precio (fecha, alojamiento de origen...), aparece el mensaje "Error al modificar el pedido"... pero el pedido se modifica igual en la BD.

**Comment by sirym** [comment]
Este error se debe a que no puede enviar el email de pedido modificado al administrador y retorna false

**Comment by sirym** [comment]
corregido
