### ISSUE TITLE
Modificar pedidos: si no se puede devolver el dinero, se tiene que poder modificar el pedido de todas formas

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#51]
Si, al hacer una modificación, la cantidad de dinero a devolver es menor que los gastos de gestión, no se puede devolver el dinero... pero se debería poder proceder a la modificación de todas formas. Ahora mismo, la aplicación muestra el mensaje, pero no deja realizar el cambio.

Debería aparecer un mensaje indicando que no se puede devolver el dinero, junto con un botón de confirmación por si el usuario quiere modificar el pedido de todas formas.

**Comment by sirym** [comment]
Corregido

**Comment by PaulJBis** [comment]
En lugar de modificar el pedido, se borra.

**Comment by sirym** [comment]
Corregido
