### ISSUE TITLE
Errorres al guardar el pedido, si se contratan varias etapas y uno se registra

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#58]
Pasos para reproducir:

1) Hacer un pedido de 3 etapas.
2) Registrarse y poner una contraseña.
3) Ir a Paypal. Al volver, aparece el mensaje "Error al guardar el pedido".

En la BD, los envíos no aparecen registrados, ni los pedidos. En uno de los casos, el cliente sí aparece (aunque sin el nombre ni el email), y en otro no.

**Comment by PaulJBis** [comment]
Si no te registras, no da error, y el pedido y los envíos se guardan... pero no el cliente (el cliente debería salir en la tabla SQL, aunque no se haya registrado).

**Comment by sirym** [comment]
Segunda parte corregida, estoy viendo la primera a ver donde esta el error

**Comment by sirym** [comment]
El primero tambien debería de ir, pero en mi localhost no envia email de registro y eso falla. Subo y pruebo en hosting

**Comment by sirym** [comment]
Confirmado, funciona correctamente
