### ISSUE TITLE
Multipedidos: las fechas y nº de bultos deben aparecer en la siguiente fase

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#59]
Al encargar varios envíos a la vez, la fecha y nº de bultos deben aparecer por defecto en el formulario para encargar la siguiente etapa.
Asímismo, el pueblo de inicio debería ser por defecto el pueblo final de la etapa anterior.

**Comment by sirym** [comment]
Primera parte arreglada. Lo de los pueblos me da un pequeño bug por los scripts de carga de hospedajes, a ver si puedo solucionarlo

**Comment by PaulJBis** [comment]
Estoy viendo que no deja modificar el hospedaje, cuando vas a añadir la segunda etapa.

Además, la fecha no debería ser la misma que la del envío anterior, sino el día siguiente.

**Comment by sirym** [comment]
fixed

**Comment by PaulJBis** [comment]
El pueblo se carga correctamente, pero el hospedaje no. Aparece por defecto el primer hospedaje del pueblo en cuestión.

**Comment by sirym** [comment]
ahora si, sorry.
