### ISSUE TITLE
En la tabla "envios", debería añadirse un campo "pueblo"

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#60]
Actualmente, en la tabla "envíos", se usa como referencia solamente el alojamiento de inicio/destino. Según el cliente, los alojamientos pueden cambiar, o no existir... Sería mejor añadir explícitamente en la tabla SQL un campo "pueblos", y usarlo para los trayectos.

**Comment by sirym** [comment]
Corregido
