### ISSUE TITLE
Eliminar campo "observaciones" en formulario en portada

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#62]
El campo "observaciones" en portada puede dar lugar a error. Eliminarlo. Eso implica varias cosas:

* Si un pedido tiene una sola etapa, las observaciones del pedido se copian al campo "observaciones" del envío en cuestión.
* Si un pedido tiene varias etapas, la primera tendrá siempre el campo de observaciones vacío. Esto es correcto (a menos que cambiemos drásticamente todo el UI).

**Comment by sirym** [comment]
Corregido
