### ISSUE TITLE
Cuando se añade una etapa doble en multipedidos, no aparece la advertencia

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#64]
Al hacer un pedido múltiple, si se añade una etapa de más de 30 km., no aparece la advertencia de que se cobrará como etapa doble.

**Comment by sirym** [comment]
Tengo dos variables de advertencia ($advertencia1 y $advertencia2) en el controller que se pueden imprimir donde se quiera como estaba antes, pero por alguna razón se han borrado de las plantillas, ¿las añado yo?

**Comment by PaulJBis** [comment]
Sí.

**Comment by PaulJBis** [comment]
El mensaje debería aparecer en la parte superior del formulario. También debería aparecer una advertencia en la columna de la izquierda. Editaré las plantillas correspondientes para ello.

**Comment by PaulJBis** [comment]
Resuelto todo, incluidos los cambios en el código.
