### ISSUE TITLE
Admin.: reformular la página de envíos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#66]
Actualmente, la página de envíos no muestra nada. Debería reformularse, teniendo en cuenta el nuevo concepto de "pedidos" que hemos introducido:

-Debería aparecer la columna de "ID de transacción de pedido" en cada envío.
-Debería haber un buscador por transacciones. No sirve de nada que el usuario llame diciendo que la ID de su transacción es "EU3MA90" si el admin. no puede buscarla usando esa ID.
-La tabla debería mostrar envíos, pero debería haber alguna forma de ver, en cada envío, el pedido al que pertenece, quizá con un pop-up. El usuario pulsa sobre un envío y aparece en un pop-up toda la ruta de la que forma parte.

**Comment by sirym** [comment]
Están completados los dos primeros puntos

**Comment by sirym** [comment]
Tercer punto hecho
