### ISSUE TITLE
Cuando el usuario pulsa "Finalizar pedido", no debería añadirle el pedido existente actualmente.

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#69]
Ahora mismo, si el usuario está haciendo un multipedido y pulsa "finalizar pedido", se le añade el pedido que tiene en la página en ese momento. Debería conducirle directamente a la página de confirmación y pago.

**Comment by sirym** [comment]
No entiendo el problema, se supone que es como "Añadir etapa y finalizar pedido". ¿Sino para que le da en la página anterior a "Añadir más etapas", si no desea que se añada la nueva?

**Comment by PaulJBis** [comment]
Tienes razón. El error no es ese, es otro.
