### ISSUE TITLE
Unir página de registro y página de datos personales

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#7]
Al introducir los datos personales, tiene que haber un checkbox dando a la gente la posibilidad de crearse un usuario y registrarse ahí mismo.

Asímismo, también debe haber una posibilidad para que la gente puede meter ahí mismo su usuario y contraseña, en vez de tener que introducir otra vez sus datos.

**Comment by sirym** [comment]
Ya se permite crear una cuenta directamente al hacer un pedido. Marcando un checkbox aparecen los input para introducir la contraseña.
