### ISSUE TITLE
Hacer lista de los emails de sistema que faltan

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#70]
-Email al cliente cuando se ha modificado un pedido suyo (con devolución de dinero).
-Email al cliente cuando se ha modificado un pedido suyo (sin devolución).

¿Alguno más?

**Comment by sirym** [comment]
He añadido emails para clientes de modificaciones (con devolucion y sin devolucion de dinero). No se me ocurre ninguno más por ahora

**Comment by PaulJBis** [comment]
Falta: enviar un email al cliente cuando una modificación implica pagar más (más bultos, más distancia…).

**Comment by sirym** [comment]
Añadido
