### ISSUE TITLE
Errores "undefined índex" al modificarse un pedido

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#74]
Cuando se modificar un pedido que no implica devoluciones, etc., aparece el siguiente error:

Notice: Undefined index: precio_nuevo in /home/caminofaky/www/NEW/app/core/controller.php on line 729

Notice: Undefined index: precio_antiguo in /home/caminofaky/www/NEW/app/core/controller.php on line 737

Notice: Undefined index: precio_nuevo in /home/caminofaky/www/NEW/app/core/controller.php on line 738

**Comment by sirym** [comment]
Corregido
