### ISSUE TITLE
Error al hacer modificar un envío y elegir un trayecto demasiado largo

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#75]
Elegimos un pedido, y modificamos un envío de forma que nos salga un trayecto demasiado largo (más de 60 km.). Aparece el error, pero aparece también debajo la opción para devolverle el dinero.

Esto no debería pasar: debería aparecer un mensaje específico para este caso, indicando que el trayecto es demasiado largo (un mensaje distinto al ya existente sobre trayectos demasiado largos).

**Comment by sirym** [comment]
Corregido
