### ISSUE TITLE
Al hacerse una devolución, debería aparecer un mensaje en pantalla indicándolo

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#76]
Al modificarse un pedido, si ello implica una devolución, debería aparecer un mensaje adicional que indique que se devolverá el dinero en los próximos días, que se ha enviado un email para ello… no sólo el mensaje de "el pedido se ha actualizado correctamente".

**Comment by sirym** [comment]
Corregido
