### ISSUE TITLE
Si un usuario que ya tenía email con nosotros se registra, el sistema no le deja

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#78]
Un usuario que ya había hecho pedidos con nosotros hace otro pedido, e intenta registrarse con el mismo email: el sistema acepta el pedido, pero ignora el registro.

**Comment by sirym** [comment]
Relacionado con #45 el error está localizado en la línea 141 de cliente.class.php

**Comment by sirym** [comment]
Corregido
