### ISSUE TITLE
Email modificaciones: información más completa

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#79]
Cuando se realiza una modificación en un pedido que no implica cambio en el precio, el email al cliente debería ser más completo, e indicar qué se ha cambiado.

Concretamente, debería aparecer el pedido completo, con todas sus etapas.

**Comment by sirym** [comment]
Completado

**Comment by PaulJBis** [comment]
Los emails que me llegan no tienen esa información. Además, me aparecen errores:

Notice: Undefined variable: datos_pedido in /home/caminofaky/www/NEW/app/core/controller.php on line 774

Notice: Undefined variable: mensaje in /home/caminofaky/www/NEW/app/core/controller.php on line 845

**Comment by PaulJBis** [comment]
Me aparecen esos errores al hacer una modificación que no implica un cambio de precio.

**Comment by sirym** [comment]
Ahora si, que no había subido los últimos cambios

**Comment by PaulJBis** [comment]
Me he equivocado yo al abrir el bug: ahora me doy cuenta de que sería mejor si esto sucediera en todos los emails de modificaciones, no sólo en los que no implican cambio de precio.

**Comment by sirym** [comment]
Corregido
