### ISSUE TITLE
Escribir sistema cron para enviar emails a administrador

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#86]
Cada noche, a las 10, se envía un email al administrador del sistema con los pedidos para el día siguiente. Hay varias opciones:

-Enviar sólo los pedidos "problemáticos" (sin repartidor asignado) pendientes para el día siguiente.
-Enviar todos los pedidos pendientes para el día siguiente, con los "problemáticos" marcados.
-Enviar los pedidos realizados durante ese día (no los pendientes para el día siguiente, sino los que se han realizado).

A consensuar con el cliente. El sistema debería ser lo bastante flexible para permitir configurar todas estas posibilidades de forma rápida.

**Comment by sirym** [comment]
añade: "wget -N -q caminofacil.net/app/modules/sendAdminEmail.php" al cron del servidor para poder hacer pruebas pon cada 5 horas por ejemplo

**Comment by sirym** [comment]
Hecho
