### ISSUE TITLE
Los usuarios registrados tienen que poder cambiar sus pedidos

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#9]
Los usuarios registrados tienen que tener la posibilidad de cambiar los pedidos que han hecho. Esto es especialmente útil cuando se trata de usuarios que programan con días (o semanas) de antelación su viaje por el Camino.

Cada vez que hagan un cambio, lógicamente, tiene que enviarse un email de alerta al administrador. Tiene que haber también un límite de fecha/hora tras el cual ya no se puedan hacer cambios (el mismo límite que para hacer pedidos).

**Comment by sirym** [comment]
Primera parte y lo de las fechas (48 horas) completado. Queda la parte del e-mail.

**Comment by sirym** [comment]
Completado

**Comment by PaulJBis** [comment]
¿La parte para que el usuario pueda editar sus pedidos pendientes también?
