### ISSUE TITLE
Admin: los pedidos ya pasados, ¿deberían salir en la lista de pedidos?

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#90]
En la pag. de admin., en la lista de pedidos, aparecen también los de días pasados, incluyendo los entregados. ¿Deberían salir por defecto o con una opción?

Falta información del cliente para saber cómo lo prefiere.

**Comment by PaulJBis** [comment]
Por defecto, tienen que salir sólo los pedidos del día en curso.

**Comment by sirym** [comment]
Hecho
