### ISSUE TITLE
No se pueden hacer pedidos en inglés

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#91]
Hacemos un pedido en inglés como usuario no registrado. Al volver del TPV virtual, nos da un error diciendo que no se ha podido guardar el pedido en la BD.

**Comment by sirym** [comment]
No me aparece el error, posiblemente se haya corregido al solucionar el anterior.

**Comment by PaulJBis** [comment]
No parece que vuelva a pasar.
