### ISSUE TITLE
Errores si volvemos del TPV sin pagar

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#93]
Hacemos un pedido, entramos en el TPV y pulsamos el botón de "Volver a comercio"… y nos aparecen estos errores:

Notice: Undefined index: nombre in /home/caminofaky/www/NEW/app/core/controller.php on line 448

Notice: Undefined index: telefono in /home/caminofaky/www/NEW/app/core/controller.php on line 449

Notice: Undefined index: email in /home/caminofaky/www/NEW/app/core/controller.php on line 450

**Comment by sirym** [comment]
Corregido
