### ISSUE TITLE
Modificar o borrar pedidos: la página de resumen es confusa

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#98]
La página de confirmación que sale antes de devolver el dinero al cliente o mandarle al TPV de nuevo es confusa: salen los pedidos borrados, los modificados no indica que lo están...

**Comment by sirym** [comment]
Ahora indica si están cancelados o modificados, falta traduccion del término 'Modificado'

**Comment by PaulJBis** [comment]
Sería mejor si aparecieran en orden cronológico (ordenados por día). Ahora mismo no lo hacen.

**Comment by sirym** [comment]
Completado

**Comment by PaulJBis** [comment]
Al modificar o borrar un pedido, sale varias veces el mensaje "Pedido actualizado correctamente", no sólo una. Si hay 5 envíos en un pedido, sale 5 veces.

**Comment by sirym** [comment]
Corregido
