### ISSUE TITLE
Arreglar errores cuando hay problemas de red o el usuario le da hacia atrás en el navegador

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil#99]
Típicas situaciones: el usuario manda un envío, hay un problema de red y lo vuelve a enviar... y aparece el mensaje "Undefined index()", y se ha añadido un envío vacío.
O el usuario se encuentra con un error y le da hacia atrás en el navegador y vuelve a pulsar.

Añadir los chequeos necesarios para que la aplicación sea robusta en esos casos.

**Comment by sirym** [comment]
Corregido
